- index.yml
This will be used by the PCF Java buildpack to look up jar URL for download.
(We should probably add a step to the release process for appending each new version to this file)
> Add index.yml that lists every release and download URL

- README.md
- build.gradle.kts
- custom/src/main/java/com/splunk/opentelemetry/InstrumentationLibraryTracerCustomizer.java
- custom/src/test/java/com/splunk/opentelemetry/InstrumentationLibraryTracerCustomizerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
Resolves #14 
Since new OTLP Collector supports passing zipkin/jeager instrumentaiton library as span tags, span processing needs to be deprecated.
- `splunk.otel.config.span.processor.instrlib.enabled` property, set to false by default
- added unit tests to confirm the behaviour
> deprecating instrumentation libary span processing via config property

- migration.md
- adds a new step to the migration workflow that includes using the OpenTracing Shim and updating the `classpath`
> Java Agent Migration - add steps for shim and classpath

- custom/src/main/java/com/splunk/opentelemetry/SplunkTracerCustomizer.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkTracerCustomizerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
Will always export the trace, even if the incoming b3 headers do not contain the `x-b3-sampled` one
> Use alwaysOn() sampler

- build.gradle.kts
add maven local repository to enable using artefacts from opentelemetry-java-instrumentation built with ./gradlew publishToMavenLocal
> add maven local repository

- matrix/.gitignore
- matrix/README.md
- matrix/build.gradle
- matrix/src/jboss-eap.dockerfile
- matrix/src/weblogic.dockerfile
- smoke-tests/src/test/java/com/splunk/opentelemetry/JBossEapSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/ProprietaryAppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomcatSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WebLogicSmokeTest.java
As Weblogic, requires local images. When present:
> JBoss EAP SmokeTest and images for the test-matrix.

- README.md
- clarify that you need to use compatible API versions to extend Splunk distribution manual instrumentation
- specify compatible otel java versions
> specify compatible otel API versions to extend manual instrumentation

- build.gradle
Upstream opentelemetry-java-instrumentation publishes snapshots to sonatype, so if we're doing a snapshot build let's include that repo.
The snapshot builds that are supposed to run 2 hours after the upstream builds have been failing, and I think this will fix that.
> Fix snapshot builds.

- README.md
- custom/src/main/java/com/splunk/opentelemetry/middleware/MiddlewareAttributeSpanProcessor.java
- custom/src/main/java/com/splunk/opentelemetry/resource/ResourceAttributesToSystemProperties.java
- instrumentation/compile-stub/README.md
- smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/logger/LoggerTestMain.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/logger/ResourceAttributesForLoggingTest.java
- smoke-tests/src/test/resources/logback.xml
Correlating logs with traces requires logging at least some resource attributes. From the agent point of view, proposed solution imposes the least performance overhead, as it requires no constant run-time overhead whatsoever and properties can be access from all major logging frameworks directly.
> Expose resource attributes as system properties to use them in logs

- agent/build.gradle
Jar files can have multiple entries with the same name. After this change there is only one entry for each name. Agent size is reduced from 39M to 30M.
> Get rid of duplicate files inside agent jar

- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
Spring Batch instrumentation is turned off by default in the upstream
> Enable experimental Spring Batch instrumentation

- instrumentation/weblogic/build.gradle
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/middleware/weblogic/WebLogicAttributeCollector.java
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/middleware/weblogic/WebLogicEntity.java
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/middleware/weblogic/WebLogicInstrumentationModule.java
- settings.gradle
- smoke-tests/src/test/java/com/splunk/opentelemetry/WebLogicSmokeTest.java
This adds collection of WebLogic-specific attributes to servlet spans, and also provides middleware name and version through `MiddlewareHolder`.
Sample output from the logging collector:
```
Attributes:
-> middleware.name: STRING(WebLogic Server)
-> middleware.version: STRING(12.2.1.4.0)
-> middleware.weblogic.server: STRING(admin-server)
-> middleware.weblogic.application: STRING(weblogic)
-> middleware.weblogic.domain: STRING(domain1)
```
No spans are created at WebLogic instrumentation level (no custom logic required), so this adds an instrumentation that only collects the attribute values, stores them as a map into `otel.middleware` ServletRequest attribute. The map contents are copied over to the span in another instrumentation where the servlet span is currently active.
WebLogic …
> Collect WebLogic specific attributes

- .github/workflows/ci.yaml
- matrix/build.gradle
- matrix/src/jboss-eap.dockerfile
- matrix/src/main/java/com/splunk/opentelemetry/appservers/javaee/GreetingServlet.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/GlassFishSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JBossEapSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JettySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/LibertySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomcatSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WebLogicSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WildFlySmokeTest.java
JBoss and WebLogic images are now pushed to private repositories in SignalFx GH org. Thus we now can test them in CI.
> Testing all proprietary Docker images in CI

- matrix/build.gradle
- matrix/src/tomee.windows.dockerfile
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomeeSmokeTest.java
Adds Windows Docker images for the same versions of TomEE that already exist for Linux and adds them as test cases for smoke test.
> Add Windows TomEE image and test

- .github/workflows/pr.yaml
We use private Docker container registry which requires authentication. But GitHub does not pass repository secrets to PRs from forks. Which in general means that we cannot use private registry during PR. Thus let's do it in builds on main branch only.
> Don't use private docker registry in PR verification

- build.gradle
- matrix/build.gradle
- matrix/src/jboss-eap.dockerfile
- matrix/src/jetty-split.windows.dockerfile
- matrix/src/jetty.windows.dockerfile
- matrix/src/openliberty.windows.dockerfile
- matrix/src/payara.windows.dockerfile
- matrix/src/tomcat.windows.dockerfile
- matrix/src/tomee.windows.dockerfile
- matrix/src/weblogic.dockerfile
- matrix/src/wildfly.windows.dockerfile
- smoke-tests/build.gradle
- smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/GlassFishSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JBossEapSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JettySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/LibertySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomcatSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomeeSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WebLogicSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WildFlySmokeTest.java
* Adds OpenJ9 images for Windows images and JBoss images.
* The logic to define images to create in `matrix/build.gradle` has been changed to be as close as possible to the logic in OpenTelemetry - only difference currently is that this one has logic to make Windows images, add pull tasks, and can be called for multiple sets of targets as it is wrapped in a function with targets as a parameter.
* Added a more concise way to list test configurations in smoke tests now to remove duplication and to merge adding multiple JDKs and VMs of the same version into one line.
* Updated `junit-jupiter` and `mockito` dependency versions to the latest which also makes them all depend on exactly the same jupiter version. This was done because for some reason after `jcenter` removal, without redownloading …
> OpenJ9 smoke test Docker images

- build.gradle
According to @iNikem it shouldn't be needed anymore. For some reason having it before `mavenCentral` slows down build by quite a bit.
> Remove jfrog oss-snapshot-local repository

- smoke-tests/build.gradle
- smoke-tests/fake-backend/build.gradle
- smoke-tests/fake-backend/src/docker/collector/windows.dockerfile
- smoke-tests/fake-backend/src/main/java/com/splunk/opentelemetry/smoketest/fakebackend/FakeBackendMain.java
- smoke-tests/fake-backend/src/main/java/com/splunk/opentelemetry/smoketest/fakebackend/FakeMetricsCollectorService.java
- smoke-tests/fake-backend/src/main/java/com/splunk/opentelemetry/smoketest/fakebackend/FakeTraceCollectorService.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/MetricsInspector.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TelemetryRetriever.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WildFlySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/AbstractTestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/LinuxTestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/windows/WindowsTestContainerManager.java
- smoke-tests/src/test/resources/otel.yaml
- smoke-tests/src/test/resources/otelcol-windows.yaml
This PR implements smoke tests verifying that our micrometer metrics get consumed by the collector correctly (and `runtime.` is added).
* Applied same fake-backend changes as in the upstream javaagent project
* Bumped otel-collector version
* Changed windows otel-collector image to contrib (has signalfx receiver)
> Verify in smoke tests that JVM metrics are exported

- README.md
- custom/src/main/java/com/splunk/opentelemetry/micrometer/GlobalTagsBuilder.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/GlobalTagsBuilderTest.java
We want to standardize on `deployment.environment` so this fixes up the README for this.  Since the micrometer tag builder was using `environment`, this creates a fallback/safeguard that prefers `deployment.environment`.
> Deployment environment

- migration.md
In looking at https://github.com/signalfx/splunk-otel-java, it has different environment variable names and system property names than the migration guide.
Updating the migration guide to match the latest version of the splunk-otel-java agent.
> Update migration.md to match github.com/signalfx/splunk-otel-java

- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstaller.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JBossEapSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WildFlySmokeTest.java
This should fix the condition 
```java
boolean metricsRegistryPresent = !Metrics.globalRegistry.getRegistries().isEmpty();
```
in metrics instrumentation modules.
> Fix main branch test failures

- smoke-tests/src/test/resources/otel.yaml
Almost the same actually: we have the signalfx receiver
> Use same otel collector config as the upstream repo

- bootstrap/build.gradle
- gradle/dependencies.gradle
- instrumentation/common/build.gradle
- instrumentation/common/src/main/java/com/splunk/opentelemetry/servertiming/ServerTimingHeader.java
- instrumentation/netty-3.8/build.gradle
- instrumentation/netty-4.0/build.gradle
- instrumentation/servlet-3-testing/build.gradle
- instrumentation/servlet/build.gradle
And use `true` as the default value.
README changes in another PR, they need to be merged after release.
> Rename the Server-Timing header property

- SECURITY.md
Based on https://github.com/signalfx/splunk-otel-collector/blob/main/docs/security.md
> Update SECURITY.md with dependabot information

- MIGRATING.md
SignalFX -> OTEL migration guide updated with latest config properties and some minor spelling / formatting fixes.
> updated SignalFX migration guide

- custom/build.gradle
- custom/src/test/java/com/splunk/opentelemetry/jaeger/JaegerThriftSpanExporterFactoryTest.java
- custom/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This was probably the only major thing that was completely not covered by the smoke tests.
> Test jaeger-thrift-splunk exporter (especially the splunk access token)

- smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JettySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomcatSmokeTest.java
As OpenTelemetry distribution supports Tomcat 10 and Jetty 11 from version 1.1.0, add their smoke tests. Unlike in OpenTelemetry, the Jetty/Tomcat specific instrumentations here did not reference Servlet API classes, therefore the use of Servlet API 5 in those versions did not require any instrumentation changes here.
> Add Jetty 11 and Tomcat 10 smoke tests

- CHANGELOG.md
- custom/build.gradle
- custom/src/main/java/com/splunk/opentelemetry/SplunkDistroVersionResourceProvider.java
- custom/src/main/resources/splunk.properties
- custom/src/test/java/com/splunk/opentelemetry/SplunkDistroVersionResourceProviderTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TraceInspector.java
Implements https://github.com/signalfx/gdi-specification/blob/main/specification/semantic_conventions.md#splunk-resource-attributes
I didn't touch the agent version (and `telemetry.auto.version`) in this PR, it's still
```groovy
attributes.put("Implementation-Version", "splunk-${project.version}-otel-${versions["opentelemetryJavaagent"]}")
```
I think that first the upstream agent has to stop using `Implementation-Version` to determine the agent version; any distro can (and probably will) override it.
> Add splunk.distro.version resource attribute

- .gitlab-ci.yml
- README.md
And remove the readme note about "development version docs" that I forgot to remove earlier.
> Fix GitLab CI build: missing zip

- agent/src/main/java/com/splunk/opentelemetry/SplunkAgent.java
- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
Fixes https://github.com/signalfx/splunk-otel-java/pull/262
This morning I realized that config is initialized after logging, so the previous solution couldn't function properly. This one does (I tested it).
> Correctly silence confusing signalfx metrics exporter INFO log

- CHANGELOG.md
- pre-release.sh
Removed links from changelog because changing them automatically is really bothersome. And I'm almost sure that nobody really uses them.
> Automatically add new version to changelog before release

- agent/build.gradle
- profiler/README.md
- profiler/build.gradle
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrRecorder.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrRecorderTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/RecordingSequencerTest.java
- settings.gradle
- testing/profiler-tests/Dockerfile
- testing/profiler-tests/README.md
- testing/profiler-tests/build.gradle
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/ProfilerSmokeTest.java
This builds on top of #273.
This makes a smoke test that fires up spring petclinic with the profiling agent enabled and ensures that JFR files are generated. It should be the foundational work for more thorough testing down the road.
In order to test, we also needed a way to configure the output directory for JFR files, so this changeset also includes that.
The smoketest has to build a spring petclinic rest image because the one in dockerhub is 2 years old and doesn't have a java 8 version with JFR.  Because of that, it's slower than I would prefer...so I'm inclined to file an issue to address that at a later time (maybe we can publish a base image like we do elsewhere).
> Profiling smoke test

- .gitlab-ci.yml
- testing/profiler-tests/build.gradle
And also remove no longer used gradle tasks from `:testing:profiler-tests`
> Disable profiler tests on GitLab because GL can't into docker

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/BasicJfrRecordingFile.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/EventProcessingChain.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JFR.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrDirCleanup.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrException.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrFileLifecycleEvents.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrPathHandler.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrRecorder.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsReader.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordedEventStream.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingEscapeHatch.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingSequencer.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/util/FileDeleter.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/BasicJfrRecordingFileTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrDirCleanupTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrFileLifecycleEventsTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrPathHandlerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrRecorderTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/RecordingSequencerTest.java
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/ProfilerSmokeTest.java
This establishes the foundation for the processing chain via the `JfrPathHandler`.  It also tracks files as they are created and deletes them after processing.  We also register a shutdown hook to not leave files behind.
A new config option `splunk.profiler.keepfiles` is available to leave the JFR files behind on disk if desired (this is useful for later development/comparison/analysis).
> Introduce JfrPathHandler and clean up files

- profiler/src/main/java/com/splunk/opentelemetry/profiler/FilterSortedRecordingFile.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/RelevantEvents.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/FilterSortedRecordingFileTest.java
JFR does not guarantee that events are time sorted.  In order to detect that a thread for a given stack frame was working as part of a span (and to link the two) we need to sort.
> Filter and sort event stream

- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrRecorder.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingEscapeHatch.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingFileNamingConvention.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrRecorderTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/RecordingEscapeHatchTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/RecordingFileNamingConventionTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/RecordingSequencerTest.java
The desire is to no longer record to files when the disk is low on space or if the number of files are backing up too much.  The `keep-files` configuration is considered a rare override that allows recording to continue even when files are backed up (also useful for development).
> Build out the recording escape hatch

- profiler/src/main/java/com/splunk/opentelemetry/profiler/BasicJfrRecordingFile.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrPathHandler.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordedEventStream.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/BasicJfrRecordingFileTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrPathHandlerTest.java
Could possibly have been holding open resources.  Not sure how this could impact the file deletion, but on some platforms maybe this could be a problem and it just seems better to close it.
> Ensure that the file is closed at stream end

- profiler/build.gradle
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrContextStorage.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/SdkCustomizer.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/ContextAttached.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrContextStorageTest.java
If the profiler is enabled, we configure the SDK with a context storage that will generate custom JFR events for scope start/stops.  This allows us to later associate stack with spans.
> add context storage to generate jfr scope tracking events

- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/ProfilerSmokeTest.java
Adds some additional details in the profiling smoke test. We look for the synthetic `otel.ContextAttached` events in the JFR files now (instead of only checking for their existence).
> look for specific events in the jfr file output

- profiler/src/main/java/com/splunk/opentelemetry/profiler/EventProcessingChain.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrPathHandler.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessor.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/SpanContextualizer.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/SpanLinkage.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/StackDescriptorLineParser.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/StackToSpanLinkage.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/ThreadContextTracker.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/ContextAttached.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/RelevantEvents.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrPathHandlerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/context/SpanContextualizerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/context/StackDescriptorLineParserTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/context/ThreadContextTrackerTest.java
We leverage the JFR events that track span thread context in order to link stack traces to active spans.
This change also introduces the `ThreadDumpProcessor` which is responsible for handling the `jdk.ThreadDump` JFR events. It doesn't yet export.
> Track span thread context and link stacks

- custom/src/main/java/com/splunk/opentelemetry/InternalRootOffSampler.java
- custom/src/main/java/com/splunk/opentelemetry/InternalRootOffSamplerProvider.java
- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- custom/src/main/java/com/splunk/opentelemetry/SplunkTracerProviderConfigurer.java
- custom/src/test/java/com/splunk/opentelemetry/InternalRootOffSamplerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/AbstractTestContainerManager.java
This is a POC sampler to gather feedback from customers. They can select this new sampler by providing `OTEL_TRACES_SAMPLER=internal_root_off` configuration option.
> Add internal_root_off sampler

- .github/publish-profiling-base-petclinic.yml
- testing/profiler-tests/Dockerfile
Hopefully resolves #276.
This creates a manually triggered GH action that will publish a base image for spring-petclinic-rest to ghcr.  This base image can then be used by the profiling smoke tests. 
Having this base image should greatly speed up build/test cycle time (largely spent in mvn downloading deps).
> Smoke tests base image

- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/ContextAttached.java
- testing/profiler-tests/build.gradle
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/profiler/ProfilerSmokeTest.java
We are not planning on using the stack data from this event, so let's omit it.
This also adds a test that confirms no stacks and enhances test code.
> No stacks in ContextAttached events.

- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrRecorder.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogEntryCreator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/EventPeriods.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrRecorderTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogEntryCreatorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/RecordingSequencerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/events/EventPeriodsTest.java
We need to report the sampling period for the backend to compute times. We source it from the JFR configuration, which does require some special parsing. We cache the values as they are parsed so that we don't have to repeat that work.
> Add the period to each log event

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- profiler/README.md
- profiler/build.gradle
- profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogsExporterBuilder.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogsExporterBuilderTest.java
Adds a new config property `splunk.profiler.logs-endpoint` that allows changing the collector endpoint for logs.
> allow logs ingest endpoint to be configured

- profiler/README.md
- profiler/build.gradle
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsOverrides.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrSettingsOverridesTest.java
This allows the user to customize/configure the JFR period for events in a somewhat generic way. The defaults are typically in the `jfr.settings` file and don't need to be changed, but especially for development this is helpful.
> Configurable JFR event periods

- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogEntryCreator.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogEntryCreatorTest.java
These are fields on `LogRecord` and the HEC exporter now knows about these and propagates them as log attributes. As such, we don't need to duplicate them now.
> remove logs workaround for trace/span id attributes.

- testing/profiler-tests/build.gradle
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/profiler/ProfilerSmokeTest.java
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/profiler/TestHelpers.java
- testing/profiler-tests/src/test/resources/collector.yaml
This stands up a collector now along with the fake backend from upstream, just like the smoke tests. It waits for log data to be present in the fake backend and then fetches/deserializes the data in order to make some assertions about it.  For now, we just verify that the period was propagated and that the sourcetype is specified and that we captured stacks for the `main` thread and the JFR thread itself.
> fetch ingested logs and make a few assertions

- .github/workflows/nightly-failed.template
I think the `@` breaks the yaml if not in a string?
> wrap the assignees in a string

- instrumentation/hikaricp/src/test/java/com/splunk/opentelemetry/hikaricp/HikariInstrumentationTest.java
Verify that meters get unregistered when the pool closes
> Add missing assertion in hikari instrumentation tests

- docs/advanced-config.md
This PR adds a new section to the advanced configuration page, "Sampling configuration", that documents the new value for `otel.traces.sampler` introduced in v1.1.0, `internal_root_off`.
> Add otel.traces.sampler parameter to the advanced configuration page

- profiler/src/main/java/com/splunk/opentelemetry/profiler/ProfilingSemanticAttributes.java
According to the [logic in HEC exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/03672d578069676c51e6bccb71519b14c0751a4e/exporter/splunkhecexporter/logdata_to_splunk.go#L72) attribute key in the log record [should be `com.splunk.sourcetype`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/03672d578069676c51e6bccb71519b14c0751a4e/internal/splunk/common.go#L29) to end up in HEC's `sourcetype` attribute.
@breedx-splk
> Fix attribute name for sourcetype in HEC.

- scripts/release.sh
This should fix the following problem:
```
> Failed to apply plugin 'nebula.release'.
> Final and candidate builds require all changes to be committed into Git.
Found unstaged changes:
[+] seckey.gpg
```
> Remove all locally changed files before running ./gradlew final

- instrumentation/khttp/src/test/groovy/com/splunk/opentelemetry/KHttpClientTest.groovy
Fixes #376
Headers map became immutable in the upstream. Instead of wrapping it and add this optional header, I decided to remove it. As khttp itself does not set it anyway.
> Fix test by removing unnecessary check

- README.md
- docs/advanced-config.md
- docs/correlating-traces-with-logs.md
- docs/faq.md
- docs/metrics.md
- docs/middleware-attributes.md
- docs/server-trace-info.md
- docs/supported-libraries.md
- docs/troubleshooting.md
The official Java OTel docs are now on our docs site: 
https://docs.splunk.com/Observability/gdi/get-data-in/application/java/get-started.html
I've pushed a small MR to update our repo README to point to the official docs when appropriate, as per our new content strategy. Docs will still remain here though, to facilitate knowledge transfer.
> Edit docs and README for docs migration to Splunk

- agent/build.gradle.kts
- bootstrap/build.gradle.kts
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/SplunkAgent.java
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- buildSrc/src/main/kotlin/splunk.shadow-conventions.gradle.kts
- custom/build.gradle.kts
- instrumentation/build.gradle.kts
- profiler/build.gradle.kts
- testing/agent-for-testing/build.gradle.kts
- testing/agent-test-extension/build.gradle.kts
... so that they're more similar to what we have in the upstream repo (and easier to maintain too)
* Removed shadowing from `custom`, `instrumentation` and `profiler`
* Moved `SplunkAgent` to `bootstrap` to avoid depending on `agent:jar`, which is disabled and I have no idea why this has worked before
> Refactor javaagent buildscripts

- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/WebengineHolder.java
- custom/src/main/java/com/splunk/opentelemetry/webengine/WebengineAttributeSpanProcessor.java
- custom/src/main/java/com/splunk/opentelemetry/webengine/WebengineAttributes.java
- custom/src/main/java/com/splunk/opentelemetry/webengine/WebengineBootstrapPackagesProvider.java
- custom/src/main/java/com/splunk/opentelemetry/webengine/WebengineTracerProviderConfigurer.java
- docs/supported-libraries.md
- docs/webengine-attributes.md
- instrumentation/glassfish/src/main/java/com/splunk/opentelemetry/webengine/GlassfishAttributesInstrumentationModule.java
- instrumentation/jetty/src/main/java/com/splunk/opentelemetry/webengine/JettyAttributesInstrumentationModule.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/webengine/LibertyAttributesInstrumentationModule.java
- instrumentation/tomcat/src/main/java/com/splunk/opentelemetry/webengine/TomcatAttributesInstrumentationModule.java
- instrumentation/tomee/src/main/java/com/splunk/opentelemetry/webengine/TomeeAttributesInstrumentationModule.java
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/webengine/weblogic/WebLogicAttributeCollector.java
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/webengine/weblogic/WebLogicEntity.java
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/webengine/weblogic/WebLogicInstrumentationModule.java
- instrumentation/wildfly/src/main/java/com/splunk/opentelemetry/webengine/WildFlyAttributesInstrumentationModule.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WebLogicSmokeTest.java
Just search and replace, no other changes
/cc @theletterf The following documentation (and link to it) should be fixed as well:
https://docs.splunk.com/Observability/gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.html#middleware-attributes-java-otel
> Rename middleware to webengine

- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
Micrometer 1.7.3 uses the latest signalfx-java released
> Bump micrometer (and signalfx-java) version

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogsExporterBuilder.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogsExporterBuilderTest.java
While we like the flexibility of having the ability to point profiling to a different ingest endpoint, we want to make it as easy as possible and minimize user effort. So now, if the user does not specify `splunk.profiler.logs-endpoint` but they do have `otel.exporter.otlp.endpoint` (like for traces/metrics), we will use that as a fallback default.
> Default endpoint to otlp endpoint

- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingFileNamingConvention.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/RecordingFileNamingConventionTest.java
This resolves #366.
Colons are not allowed in filenames in Windows. 😎
> replace colons with underscores to support windows

- .github/workflows/ci.yaml
- matrix/build.gradle.kts
It looks like Weblogic containers completely disappeared from GHCR, we'll have to generate them from scratch and upload them again.
> Re-enable proprietary appserver (JBoss EAP) tests

- instrumentation/hikaricp/build.gradle.kts
I've noticed that sometimes, completely randomly, hikari instrumentation tests fail with an instrumentation error. I tried running it tens of times locally, couldn't reproduce. On the CI there's nothing in logs, no assertion message - so I configured gradle to print out everything to stdout, maybe that'll help with pinpointing the problem.
> Temporary change to make debugging hikari easier

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
A new `lycheeverse/lychee:latest` tag was pushed ~9 hours ago, and it's completely broken - it fails with the following error
```
standard_init_linux.go:228: exec user process caused: no such file or directory
```
Anyway, I find it REALLY BAD that a concrete `lycheeverse/lychee-action@v1.0.8` version depends on a "latest" tag of some other image.
> Disable lychee checks

- bootstrap/build.gradle.kts
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/GaugeSemanticConvention.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxAttributesHelper.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxMetricsWatcher.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxQuery.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/MetersFactory.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxMetricsWatcherIntegrationTest.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxMetricsWatcherTest.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxQueryTest.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/TestClass.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/TestClassMBean.java
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- docs/metrics.md
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/instrumentation/liberty/LibertyMetricsInstaller.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/instrumentation/liberty/metrics/LauncherDelegateImplInstrumentation.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/instrumentation/liberty/metrics/LibertyMetricsInstrumentationModule.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/instrumentation/liberty/metrics/ThreadPoolMetrics.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/instrumentation/liberty/webengine/LibertyAttributesInstrumentationModule.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/LibertySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/MetricsInspector.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/LinuxTestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/TestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/TestImage.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/windows/WindowsTestContainerManager.java
- smoke-tests/src/test/resources/liberty-with-monitor.xml
I couldn't really test those metrics in this PR, because the OTel Liberty image does not have the `monitor-1.0` feature enabled and it doesn't register the thread pool mbean.
> Implement metrics for IBM WebSphere thread pools

- smoke-tests/build.gradle.kts
- smoke-tests/src/test/java/com/splunk/opentelemetry/LibertySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/LinuxTestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/ResourceMapping.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/TestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/windows/WindowsTestContainerManager.java
Copied from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3868
> Allow mapping resource to multiple container paths in smoke tests

- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/jmx/JmxListener.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/jmx/JmxQuery.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/jmx/JmxWatcher.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxMetricsWatcher.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/jmx/JmxQueryTest.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/jmx/JmxWatcherTest.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxMetricsWatcherIntegrationTest.java
- bootstrap/src/test/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/jmx/JmxMetricsWatcherTest.java
- bootstrap/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/instrumentation/liberty/metrics/ThreadPoolMetrics.java
All the JMX-related logic went into `JmxWatcher`, everything metrics was left in `JmxMetricsWatcher`. The aim of this PR (besides making the code a bit nicer) is to make it possible to use `JmxWatcher` for general purpose debugging and ad-hoc testing
> Refactor JmxMetricsWatcher and split its responsibilities

- profiler/README.md
As part of #406 we flipped to disabled by default but the readme didn't get updated.
> profiler TLABs :: readme was wrong

- profiler/build.gradle.kts
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ConfigurationLogger.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsOverrides.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogsExporterBuilder.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationLoggerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationTest.java
This helps us to do troubleshooting and provide additional support.
> log the profiler config at agent start.

- profiler/src/main/java/com/splunk/opentelemetry/profiler/JFR.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/SdkCustomizer.java
Tested on 8u212 and sure enough, there were some exceptions in the logs about unknown JFR classes. I added some additional preventions here and confirmed that the exceptions no longer happen. Also confirmed that JFR still works on newer JVMs.
> Safer JFR availability checks

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/AgentInternalsFilter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessor.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/AgentInternalsFilterTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessorTest.java
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/profiler/ProfilerSmokeTest.java
Most users will find little value in these and probably won't want to pay for ingest/collection, so let's omit them.
This is a first-pass. It is expected that we will iterate on the list of things being dropped.
> Profiler omits some agent internal threads

- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingSequencer.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/util/StackSerializer.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/util/StackSerializerTest.java
Apparently stack frames can have null methods although javadoc https://docs.oracle.com/javase/9/docs/api/jdk/jfr/consumer/RecordedFrame.html#getMethod-- states otherwise.  I discovered this while investigating why test added in https://github.com/signalfx/splunk-otel-java/pull/436 is flaky.
This pr also adds catching all exceptions to `RecordingSequencer. handleInterval`. This method is invoked periodically by `ScheduledExecutorService` if it fails it will not be invoked again so we should not let it fail.
> Fix profiler NPE

- .github/workflows/publish-otel-collector-contrib-windows.yaml
- smoke-tests/otel-collector-contrib-windows/Dockerfile
- smoke-tests/otel-collector-contrib-windows/build.sh
Resolves https://github.com/signalfx/splunk-otel-java/issues/137
Ideally we should use splunk-otel-collector everywhere, but that needs to wait until splunk-otel-collector has a Windows docker image.
> Build splunk-otel-collector Windows docker image for tests

- profiler/src/main/java/com/splunk/opentelemetry/profiler/FilterSortedRecordingFile.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/RelevantEvents.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/FilterSortedRecordingFileTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/events/RelevantEventsTest.java
If TLAB events end up in the file (through interference from other recordings, for example), we still don't want to treat them as relevant. This guards it with config.
> TLAB events are only relevant if enabled in config

- README.md
- docs/server-instructions.md
Our current Java instrumentation docs lack specific instructions for hooking up the -javaaagent with the startup scripts of the application servers such as Tomcat or Weblogic. This is a know issue; each server requires separate instructions.
This PR adds instructions for the supported Java servers.
> Add java server instrumentation instructions

- profiler/src/main/java/com/splunk/opentelemetry/logs/InstrumentationLibraryLogsAdapter.java
- profiler/src/main/java/com/splunk/opentelemetry/logs/ResourceLogsAdapter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ProfilingSemanticAttributes.java
- profiler/src/test/java/com/splunk/opentelemetry/logs/InstrumentationLibraryLogAdapterTest.java
- profiler/src/test/java/com/splunk/opentelemetry/logs/ResourceLogAdapterTest.java
There was a note from a while back. Let's remove our own hardcoded version and use upstream.
> Leverage SCHEMA_URL from upstream

- profiler/src/test/java/com/splunk/opentelemetry/logs/ResourceLogsAdapterTest.java
Just a class rename (it didn't match the class under test).
`ResourceLogAdapterTest` -> `ResourceLogsAdapterTest`
> Rename ResourceLogsAdapterTest to match class under test

- profiler/src/main/java/com/splunk/opentelemetry/profiler/AgentInternalsFilter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/StackTraceFilter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessor.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ThreadDumpToStacks.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/AgentInternalsFilterTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/StackTraceFilterTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ThreadDumpToStacksTest.java
- profiler/src/test/resources/thread-dump1.txt
- settings.gradle.kts
- testing/jmh-benchmarks/build.gradle.kts
- testing/jmh-benchmarks/src/jmh/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessorBenchmark.java
- testing/jmh-benchmarks/src/main/java/com/splunk/opentelemetry/profiler/JfrFileMaker.java
- testing/jmh-benchmarks/src/main/java/com/splunk/opentelemetry/profiler/old/AgentInternalsFilter.java
- testing/jmh-benchmarks/src/main/java/com/splunk/opentelemetry/profiler/old/ThreadDumpProcessor.java
The single large string instance obtained from the `jdk.ThreadDump` event has to be parsed so that we can send separate stack traces to ingest. Previously, we just simply called `.split("\n\n")` on this. The regex might be computationally expensive, whatever, but we definitely know that the split is allocating a lot of strings that get thrown away immediately when agent internal threads are omitted (default).
So, this creates a stateful parser to help handle this. We only create those smaller substrings in the event that we can parse a stack and pass the filters. This also adds a few more thread names to the filter list.
> Improve jdk.ThreadDump content parsing

- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrRecorder.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrRecorderTest.java
`FlightRecorder.getFlightRecorder().takeSnapshot()` contains all recorded data which includes events that we have already processed.
> Limit jfr dump content

- README.md
- custom/src/main/java/com/splunk/opentelemetry/SplunkTracerProviderConfigurer.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkTracerProviderConfigurerTest.java
Turns out it was just the max attribute value length, we already had implemented everything else that was introduced in 1.1.0.
> Update project to GDI spec version 1.1.0

- profiler/src/main/java/com/splunk/opentelemetry/profiler/ConfigurationLogger.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationLoggerTest.java
The jdk prefix should have been omitted, so we were logging the wrong value even when the user followed the docs.
> Profiler: Log the config for the correct key, and do it as duration

- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/LinuxTestContainerManager.java
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/profiler/ProfilerSmokeTest.java
The problem with otel/opentelemetry-collector-contrib:latest has been resolved so we can switch back to using it.
> Switch back to collector latest

- smoke-tests/src/test/java/com/splunk/opentelemetry/WebSphereSmokeTest.java
Fix copy-paste mistake in websphere test name. Fix capitalization of websphere attributes class name to be consistent with other classes.
> Fix test name

- profiler/build.gradle.kts
- profiler/src/main/java/com/splunk/opentelemetry/logs/LogEntry.java
- profiler/src/main/java/com/splunk/opentelemetry/logs/LogEntryAdapter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrContextStorage.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogEntryCreator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/SpanContextualizer.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/SpanLinkage.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/StackToSpanLinkage.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/ContextAttached.java
- profiler/src/test/java/com/splunk/opentelemetry/logs/BatchingLogsProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/logs/InstrumentationLibraryLogAdapterTest.java
- profiler/src/test/java/com/splunk/opentelemetry/logs/LogEntryAdapterTest.java
- profiler/src/test/java/com/splunk/opentelemetry/logs/ResourceLogsAdapterTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogEntryCreatorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/StackToSpanLinkageProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/context/SpanContextualizerTest.java
This will be the first in a series of incremental enhancements that move us in the direction of using logs from upstream (rather than our own implementation).
Two main things in this PR:
* Our core log model object is called `LogEntry` and it is a concrete class with no interfaces. This PR lets that class implement the upstream `LogData` class. In doing this, it made sense to change the individual `spanId` and `traceId` fields to `spanContext`, which also made sense to make the other change....
* Add a new byte field for `traceFlags` into the `ContextAttached` events in order to more accurately reinflate the span context.
Following PRs can migrate usages of `LogEntry` to the interface, and once the direct references are gone we can migrate to the upstream data object.
> Begin using upstream logs sdk

- profiler/src/main/java/com/splunk/opentelemetry/profiler/StackTraceFilter.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/StackTraceFilterTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ThreadDumpToStacksTest.java
When profiling with JFR, a good number of call stacks consist entirely of JVM internal frames. The stacks are expensive to ingest and do not offer much value to the profiling user.
There will be follow-up efforts to allow this to be quantified and to allow the user to override this behavior.
> Add filter for jvm internal stack traces

- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/StackTraceFilter.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/StackTraceFilterTest.java
We need a config item here so that we can compare data volume and overhead with/without jvm internal stacks.
> Add config to include jvm internal stacks

- docs/faq.md
Just in case 2 days isn't enough - like in the case of the last release, where we purposefully waited for a patch release in the upstream.
CC @flands
> Extend the release SLA for a couple of days

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ConfigurationLogger.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsOverrides.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/RelevantEvents.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationLoggerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogsExporterBuilderTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/events/RelevantEventsTest.java
An identical copy of #573 in case this is a faster route to getting the changes merged before the commits are signed. Feel free to close this if #573 gets merged first. Similarly, if this gets merged then we should close #573.
> Add profiler memory.enabled option (copy changes from #573)

- CHANGELOG.md
- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ConfigurationLogger.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrRecorder.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsOverrides.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingSequencer.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationLoggerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrSettingsOverridesTest.java
Resolves #572 
GDI spec is updated, so we should now use `splunk.profiler.call.stack.interval`. To be backwards compatible, the old setting is marked deprecated but still functions.
> Rename profiler thread dump config setting

- Dockerfile
- scripts/release.sh
This is needed by auto-instrumentation in environments like kubernetes.
> Publish agent as docker image

- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
rename `allocationSize` -> `memory.allocated` and remove `tlabSize`
> Rename allocation size attribute

- docs/advanced-config.md
- docs/correlating-traces-with-logs.md
- docs/faq.md
- docs/metrics.md
- docs/server-trace-info.md
- docs/supported-libraries.md
- docs/troubleshooting.md
- docs/webengine-attributes.md
This PR fixes the link to CONTRIBUTING.md in docs notices. It was broken.
> Fix link to CONTRIBUTING.md

- docs/metrics.md
I've had to dig for this more than once now and we didn't make it too easy to find...so I've added a brief note near the top of `metrics.md` in docs with a link to the detailed (advanced) docs.
> Add short note about metrics default state and how to enable.

- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/util/StackSerializer.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/util/StackSerializerTest.java
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/profiler/ProfilerSmokeTest.java
The format of stacks coming in for TLAB events didn't conform to GDI spec, so this fixes that up. They should look much more like the other stack traces now. Also added a few more checks in the smoke tests around the data contained in the tlab logs.
> Profiler - Fix TLAB stack format

- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfig.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfigTest.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
Turn on metrics automatically but only when _memory_ profiling is enabled. cpu profiling doesn't need it yet.
#604 was too aggressive, this relaxes it just to memory profiling.
> Memory profiling implies metrics

- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
We don't need the upstream micrometer instrumentation, we're using our own; I also disabled the logging appender instrumentations - we're not exporting the logs signal yet, and they get called for every log statement so it's probably better to turn them off right now.
> Disable some unnecessary instrumentations

- scripts/install-release-deps.sh
The previous release job failed as it did not have docker installed. This PR installs docker as a release dependency.
> Install docker in CD release step

- instrumentation/jvm-metrics/build.gradle.kts
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/AllocatedMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/GcMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsInstaller.java
- instrumentation/jvm-metrics/src/test/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsTest.java
This pr adds two new metrics
- total amount of memory allocated. When plotted with `rateofchange` function this should show memory allocation rate. It is similar to existing `runtime.jvm.gc.memory.allocated` metric. Allocated memory is computed using `ThreadMXBean`, short lived threads are not tracked.
- sum of heap usage before gc - heap usage after gc
> Add memory allocation and gc metrics

- scripts/release.sh
This is useful for customers and services like kubernetes operator to
target latest minor/patch version from a major series.
> Tag docker images with the major/stable version

- instrumentation/khttp/src/main/java/com/splunk/opentelemetry/instrumentation/khttp/KHttpHttpClientHttpAttributesGetter.java
- instrumentation/khttp/src/main/java/com/splunk/opentelemetry/instrumentation/khttp/KHttpSingletons.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/EventProcessingChain.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/EventProcessingChainTest.java
PriorityQueue does not have a guarantee ordered iteration. This caused a bug that prevented the JFR events from being dispatched in time order. This has considerable consequences. 
The PriorityQueue was well intentioned as part comments in of #467 (commit d7fb40ac84b8a965bc746299ca155e916acf81dc), but ultimately introduced this problem.
Note: The test is only a loose guarantee. It is possible to reorder the events and still have the test pass, due to the inconsistency of iteration.
> Fix bug related to iteration over PriorityQueue

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ConfigurationLogger.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/StackTraceFilter.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationLoggerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/StackTraceFilterTest.java
Since having to separately assign two options for enabling internal stack traces (agent internals vs JVM internals) can be confusing, there is now an option that toggles both: `splunk.profiler.include.internal.stacks`. The previous options still exist internally, but the new option is the default value for them if they are not explicitly specified. As setting them separately could only have very corner case uses, the documentation now only mentions the unified toggle.
Previously the option to enable agent internal stack traces also made JVM internal traces be reported. This was rather unintuitive, and therefore changed it so that JVM internal traces can still stay excluded even if agent internal traces are included.
Fixed tests using a different stack trace format (whitespace difference) …
> profiler: Unified option for enabling internal stacks, fix logic of enabling separately

- .github/workflows/nightly.yaml
Fixes #662 
Fixes #661 
🤞 
I suspect our smoke tests just take too long for the night build to finish; let's split them out (same as in CI/PR builds) and hope that'll fix the issue.
> Split out smoke-tests in nightly build

- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/instrumentation/weblogic/metrics/ServerLifecycleListenerInstrumentation.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WebLogicSmokeTest.java
Resolves https://github.com/signalfx/splunk-otel-java/issues/673
Resolves https://github.com/signalfx/splunk-otel-java/issues/668
Resolves https://github.com/signalfx/splunk-otel-java/issues/667
Weblogic metrics are registered fairly late in startup process, waiting until running message is seen should ensure that they are registered before our tests start.
> Wait for weblogic to start

- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
Shouldn't be needed since https://github.com/signalfx/gdi-specification/commit/b09e176ca3771c3ef19fc9d23e8722fc77a3b6e9
> Remove bogus info from allocation stacks

- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsInstaller.java
- instrumentation/jvm-metrics/src/test/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsTest.java
@gsmirnov-splk please review
Should we always enable this or only when memory profiling is enabled?
> Add micrometer heap pressure metrics

- .github/workflows/publish-profiling-petclinic-base.yml
- smoke-tests/profiling-base-petclinic/linux/Dockerfile
- smoke-tests/profiling-base-petclinic/windows/Dockerfile
- smoke-tests/profiling-base-petclinic/windows/build.sh
Added workflows for publishing Windows and Linux versions of the profiler smoke test base Petclinic image for each of JDK 8, 11 and 17.
> Profiler: Smoke test matrix image publishing

- .github/workflows/publish-profiling-petclinic-base.yml
Fixed wrong path passed the wrong path to Dockerfile in profiler smoke test image publishing workflow (due to https://github.com/signalfx/splunk-otel-java/pull/697 ).
> Fixed wrong path to Dockerfile in workflow

- smoke-tests/profiling-base-petclinic/linux/Dockerfile
The legacy adoptopenjdk images don't have JDK 17, which caused building of that version of the image to fail.
> profiler: Use temurin as base image for profiler smoke test

- profiler/README.md
There are some corner cases regarding `splunk.profiler.enabled` option which can be confusing and were not properly explained in the README before:
- Can you specific features (like `splunk.profiler.memory.enabled`) without enabling the main profiler toggle (`splunk.profiler.enabled`)? - answer is currently NO
- Is it possible to enable memory profiling but not call stack/thread dump collection? - answer is currently NO
This is intended as a clarification of the current behavior without any actual changes. There will probably be a follow-up to this to allow disabling call stack collection, at which point this explanation in the readme will be changed to reflect that.
> profiler: Explain splunk.profiler.enabled behavior in readme

- custom/src/main/java/com/splunk/opentelemetry/micrometer/GlobalTagsBuilder.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/GlobalTagsBuilderTest.java
This was asked for by the folks working on the profiling features.
> Add host.name and container.id to micrometer tags

- gradle.properties
It is commented out in otel agent also. See https://youtrack.jetbrains.com/issue/IDEA-272594/Gradle:-The-CompileOptions.annotationProcessorGeneratedSourcesDi
> Disable failing build on gradle warning

- profiler/build.gradle.kts
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JFR.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ProfilingSemanticAttributes.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/allocation/exporter/PlainTextAllocationEventExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/allocation/exporter/PprofAllocationEventExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/exporter/PprofCpuEventExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/exporter/StackTraceParser.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/pprof/Pprof.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/util/StackSerializer.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/exporter/StackTraceParserTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/util/StackSerializerTest.java
@gsmirnov-splk @vovencij please review
> Add an option to limit stack depth

- scripts/release.sh
The only sensible way of automating this seems to be through commit messages (it's surprisingly hard to create a tag on main once a given PR is merged), so I added a `[agent-version-update]` "tag" that'll trigger the overhead test run.
Related to https://github.com/signalfx/splunk-otel-java-overhead-test/pull/45
> Run overhead tests automatically based on the commit message

- profiler/src/main/java/com/splunk/opentelemetry/profiler/pprof/Pprof.java
Key class instances require less memory than string concatenation
> Use a specialized class instead of string as key in pprof tables

- custom/src/main/java/com/splunk/opentelemetry/RealmAccessTokenChecker.java
- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfig.java
- custom/src/test/java/com/splunk/opentelemetry/RealmAccessTokenCheckerTest.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkConfigurationTest.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfigTest.java
Setting a `SPLUNK_REALM` value that is not `none` now changes the default values of the following properties:
- `otel.exporter.otlp.traces.protocol` to `http/protobuf` as the ingest URL only supports protobuf over HTTP, not gRPC.
- `otel.exporter.otlp.traces.endpoint` to `https://ingest.REALM.signalfx.com/v2/trace/otlp`
- `otel.exporter.jaeger.endpoint` to `https://ingest.REALM.signalfx.com/v2/trace`
- Splunk metrics endpoint to `https://ingest.REALM.signalfx.com` (the path is appended in sender implementation)
This is implemented by setting defaults conditionally in `SplunkConfiguration`. The reason why this is not done in `SplunkAgent` like some other configuration options is that it would require conditionally checking that we do not accidentally overwrite any explicitly provided …
> Add support for SPLUNK_REALM environment variable/property

- smoke-tests/src/test/java/com/splunk/opentelemetry/ProfilerSmokeTest.java
Hopefully fixes sporadic profiling test failures. Jfr files are read in `spanThreadContextEventsFound` and `contextEventsHaveStackTraces` the latter is called right after the former. `spanThreadContextEventsFound` already makes the file readable. If a jfr file is created after `spanThreadContextEventsFound` and before `contextEventsHaveStackTraces` then `contextEventsHaveStackTraces` could observe a jfr file that is not readable.
> Make jfr file readable before attempting to open it

- custom/src/main/java/com/splunk/opentelemetry/micrometer/OtelNamingConvention.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/OtelNamingConventionTest.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/AllocatedMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/GcMemoryMetrics.java
- instrumentation/jvm-metrics/src/test/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsTest.java
This changes the profiling memory allocation metrics names. It wasn't immediately clear from the names that these metrics are monotonically increasing (cumulative) values, so I added `cumulative` and removed the `experimental` namespace.
I am not married to these names, so please feel free to suggest some improvements. The goal was to keep them in line with the [otel spec jvm metric names](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics), even tho these are not yet present.
> Change metric names for memory allocation/reclaim.

- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/AllocatedMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/GcMemoryMetrics.java
These counters should produce the same values with rate/sec rollup as we currently get from gauge with rate of change transform. One problem with doing this change is that once an instrument has been change as gauge the change to counter won't be picked up so might need to rename once more.
@gsmirnov-splk your call whether you want these as counter
> Use counter instead of gauge for allocation metrics

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ConfigurationLogger.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsOverrides.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationLoggerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrSettingsOverridesTest.java
This config setting has been deprecated for some time. Time to remove it.
> Remove deprecated splunk.profiler.period.{eventName} config setting

- profiler/README.md
Add `splunk.profiler.cpu.data.format` and `splunk.profiler.memory.data.format` config items to the profiling readme.
> Add data format config items to the profiling readme. 

- CHANGELOG.md
- README.md
- profiler/README.md
I believe that doc team decided that it should be called Splunk OpenTelemetry Collector a while ago
> Use collector instead of connector

- custom/build.gradle.kts
Prevent pulling in gson classes from jaeger dependency.
> Exclude gson (mitigate CVE-2022-25647)

- README.md
- docs/advanced-config.md
I assume we will want to keep support for `jaeger-thrift` until the SmartAgent is deprecated in December. Once that happens, we can remove `jaeger-thrift` from our distro. 
This change just adds a deprecation notice about that and removes the mention from the front page (to discourage creating new user dependencies on it).
> Add deprecation notice and remove mention from front readme

- .gitlab-ci.yml
Since we run CI in gitlab, let's use our internal read-thru caching repository to prevent overwhelming dockerhub (and failing our own builds)
> Use splunkdev for docker

- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkConfigurationTest.java
Turns out we forgot to disable that one, it installs the OTel micrometer registry in Spring Boot.
> Turn off the spring-boot-actuator-autoconfigure instrumentation

- .gitlab-ci.yml
We have to use this ref name for now.
> Fix ref name for fossa scan

- smoke-tests/src/test/java/com/splunk/opentelemetry/JBossEapSmokeTest.java
Resolves https://github.com/signalfx/splunk-otel-java/issues/896
> Disable service name detection test on jboss eap

- deployments/cloudfoundry/index.yml
- scripts/update-version-after-release.sh
Realized that we don't need the `-all` suffix on the jar URLs.
I can rebase this after #920.
> remove -all suffix from agent jars

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
Some users have permissions issues when writing to the current working directory. This changes the default location to System.getProperty("java.io.tmpdir") which is the system temp dir. We think more users will have success with this instead.
> Change default `splunk.profiler.directory` 

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/splunk.spotless-conventions.gradle.kts
- instrumentation/khttp/src/main/java/com/splunk/opentelemetry/instrumentation/khttp/KHttpHttpClientNetAttributesGetter.java
- profiler/build.gradle.kts
I noticed a few warnings in the builds for #959 and #956, so this addresses those. The only wildcard import in kts files was in the profiling build script, and it wasn't even used so I just removed it.
> Kotlin warnings

- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
This will bump the `jackson-databind` dependency version to 2.13.4.2
Fixes #945
> Bump signalfx-java version (and jackson-databind transitively)

- settings.gradle.kts
With the upgrade to `3.11.3` in #977, local builds began prompting to accept the license agreement. This looked especially strange in IntelliJ, where it seemed like builds were just hung (which I guess they were, hung waiting for human input).
Anyway, this short circuits the prompt for local builds.
> Fix local build prompting for gradle enterprise 👎🏻 

- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/JvmMemory.java
New Micrometer was issuing deprecation warnings for this import, which I'm sure was just an auto-import mistake. Change to `javax.annotation.Nullable`.
> Change deprecated import

- .github/workflows/ci.yaml
- .github/workflows/nightly.yaml
- .github/workflows/pr.yaml
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Don't use ::set-output in GHA, it's deprecated

- buildSrc/build.gradle.kts
Reverts signalfx/splunk-otel-java#1031
Fixes #1032 
Fixes #1035
We'll need to update this to the latest snapshot version together with the upstream agent; the `muzzle` module has changed a bit since the release, and it affects the plugins.
> Revert "Bump gradle-plugins from 1.21.0-alpha-SNAPSHOT to 1.22.0-alpha-SNAPSHOT"

- CHANGELOG.md
- README.md
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- deployments/cloudfoundry/buildpack/README.md
I also updated the GDI spec version to 1.4.0 -- there weren't any changed that affected the javaagent anyway.
> Prepare for 1.19.0

- settings.gradle.kts
This reverts commit 36cba588128b46239c38cf921ab6d79e40483b0a.
Looks like there's an issue with the newer version:
```
Exception in thread "docker-java-stream--1183027921" java.lang.UnsatisfiedLinkError: 'java.lang.String com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion()'
```
> Revert "Bump com.bmuschko.docker-remote-api from 9.0.1 to 9.1.0 (#1043)"

- .github/workflows/publish-docker-image-ghcr.yml
- Dockerfile-ghcr
This is related to #647.
We want to be publishing a more minimal docker layer that only contains our released agent jars. Also, we are switching from quay.io for open source images, so this sets up a GHA workflow that triggers on release creation and builds/publishes to GHCR.
There is a [sample repo here](https://github.com/breedx-splk/ghcr-publish-exp) that I used in development. You can look at the actions there and see the packages that result.
> Add workflow to publish to GHCR

- Dockerfile-ghcr
In better keeping with the [upstream k8s operator](https://github.com/open-telemetry/opentelemetry-operator/blob/65c2bec1aeeff08c42ca2d31892af0ff06fa4c65/autoinstrumentation/java/Dockerfile#L2), we create a symlink in the root of the container whose name is `javaagent.jar` which matches the expectation.
> Create symlink to agent jar in ghcr container

- .github/workflows/ci.yaml
- .github/workflows/nightly.yaml
- .github/workflows/pr.yaml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- dependencyManagement/build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- instrumentation/khttp-0.1/build.gradle.kts
- instrumentation/khttp-0.1/src/main/java/com/splunk/opentelemetry/instrumentation/khttp/KHttpHttpClientHttpAttributesGetter.java
- instrumentation/khttp-0.1/src/main/java/com/splunk/opentelemetry/instrumentation/khttp/KHttpSingletons.java
- instrumentation/micrometer-testing/build.gradle.kts
- profiler/build.gradle.kts
- settings.gradle.kts
* Updates to gradle 8+
* Update shadow jar to latest (supersedes #1140 #1143)
* Update protobuf (supersedes #1129)
* Update nexus plugin (supersedes #1149)
Resolves #1151
> Build fix amalgamation and dep upgrades

- scripts/propagate-version.sh
The overhead repo is now offline, so remove this step from the release process.
> Remove overhead version PR from release script

- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/SplunkAgent.java
- custom/build.gradle.kts
- custom/src/main/java/com/splunk/opentelemetry/logging/SplunkSlf4jLoggingCustomizer.java
- dependencyManagement/build.gradle.kts
- smoke-tests/src/test/java/com/splunk/opentelemetry/SecurityManagerSmokeTest.java
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7983 adds an experimental option to improve compatibility with security manager to upstream agent. This pr adds a test for running our agent with enabled security manger and moves calls to methods that require privileges, such as `System.setProperty` and `System.getenv`, to a later point where agent code has the required privileges.
> Fix agent startup with security manager

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ProfilingSemanticAttributes.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/allocation/exporter/PprofAllocationEventExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/exporter/PprofCpuEventExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/exporter/PprofLogDataExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/pprof/Pprof.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/LogsInspector.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/ProfilerAllocationSanityTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/ProfilerSmokeTest.java
- testing/jmh-benchmarks/src/jmh/java/com/splunk/opentelemetry/profiler/ThreadDumpProcessorBenchmark.java
The enum only had one value remaining, so it makes sense to just remove it.
The profiling README also still had reference to the config items for choosing data format, so those are also now removed.
> Remove data format, standardize on only pprof.

- Dockerfile-ghcr
According to the [dependabot docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker), we might be able to get dependabot to PR into the helm chart repo after we publish.
To help facilitate this, let's add these required tags.
> Add labels to help dependabot

- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkConfigurationTest.java
This should make any testing/usage a bit easier.
> Only disable logging instrumentations when logs exporter is not set

- scripts/install-gh-deps.sh
- scripts/propagate-version.sh
New version of #1241 
In order for the helm charts to get updated, we need to push a PR after each release.
I really wanted to use yq to do yaml editing instead of sed, but sadly both flavors I found and tried have outstanding issues around keeping existing comments and formatting. I didn't want a one-line version change to result in thousands of lines touched or important comments removed.
Ok, after talking about this with the collector helm chart team, the other approach doesn't work because it requires running this `make render` command to update the templates...and dependabot won't work with that. So we'll just hack it up.
> Helm chart PR after release

- .github/workflows/pr.yaml
to make pr builds a bit faster lets skip windows tests unless pr is tagged with `test windows`
> Skip windows smoke tests on pr build

- scripts/propagate-version.sh
Based on[ this discussion](https://github.com/signalfx/splunk-otel-collector/pull/3304#issuecomment-1603226793), the collector team will be adding their own polling mechanism, so we are no longer on the hook for this.
> No longer push a PR to collector, it will poll

- smoke-tests/src/test/java/com/splunk/opentelemetry/LogsInspector.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/OtlpLogsSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TraceInspector.java
Since we are already testing that `traceId` gets attached to autoinstrumented log entries, check for `spanId` as well.
> Test spanId in log correlation smoke test

- custom/src/main/java/com/splunk/opentelemetry/TruncateCommandLineWhenMetricsEnabled.java
- custom/src/test/java/com/splunk/opentelemetry/TruncateCommandLineWhenMetricsEnabledTest.java
Similarly to `process.command_line` we need to limit the size of `process.command_args`
> Truncate process.command_args

- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/AllocatedMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/GcMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/micrometer/MicrometerAllocatedMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/micrometer/MicrometerGcMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelAllocatedMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelGcMemoryMetrics.java
Rework #1427 due to goofy merge shenanigans.
There was a case in the field on an IBM J9 JVM, where an instance returned from `ManagementFactory.getThreadMXBean()` could not be cast safely to the `com.sun.management.ThreadMXBean`, even thought that class can be found on the classpath.
It looks like [other implementations](https://github.com/elastic/apm-agent-java/issues/505) have also encountered this, and so this fix is inspired by those [other workarounds](https://github.com/felixbarny/apm-agent-java/commit/bb7f7712ca7c4126aeb3d22709777ba7684ab14a).
> Verify class compatibility before attempting cast

- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/GcMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsInstaller.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelGcMemoryMetrics.java
Add otel version of metrics used by profiling
> Add otel version of profiling metrics

- smoke-tests/build.gradle.kts
- smoke-tests/src/test/java/com/splunk/opentelemetry/HecTelemetryInspector.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/HecTelemetryRetriever.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/OtlpLogsSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/AbstractTestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/LinuxTestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/TestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/windows/WindowsTestContainerManager.java
- smoke-tests/src/test/resources/otel.yaml
Added HEC exporter configuration and a MockServer fake backend as part of the normal smoke test setup - although only logs are exported there at the moment. This enables reusing the same container setup and even the same test for checking HEC exporter output.
Could not find a MockServer image for Windows at the moment, so the HEC part of the test is disabled on Windows for now.
> Test for log correlation from HEC exporter as well

- custom/src/main/java/com/splunk/opentelemetry/logging/SplunkSlf4jLoggingCustomizer.java
Silence a non-fatal warning when starting profiler with jdk21. Also fixes log level setting for `org.apache.http.impl.execchain.RetryExec`
> Silence profiler warning on jdk21

- buildSrc/src/main/kotlin/splunk.muzzle-conventions.gradle.kts
upstream examples don't have it, but they have `opentelemetry-javaagent-extension-api`
> Remove logback from muzzle-tooling

- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/AllocatedMemoryMetrics.java
Check for mxBean compatibility ahead of checking whether Allocated Memory is enabled. This is related to #1435 .
> fix: Check mxBean compatibility

- buildSrc/src/main/kotlin/splunk.instrumentation-conventions.gradle.kts
Testing extension already sets up exporter for tests adding the otlp exporter flag only adds stack traces with export failures to test output.
> Don't set metrics exporter to otlp for tests

- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- instrumentation/jvm-metrics/build.gradle.kts
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsInstaller.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
As discussed with @akubik-splunk in preparation for the potential removal of the thread pool metrics I'm going to make memory profiling enable only the profiling metrics and leave the thread pool metrics disabled.
> Don't enable thread pool metrics with profiler

- .github/workflows/ci.yaml
this is what upstream used before changing adding `release/` prefix to the release branch name
> Run ci build on patch release branch

- .fossa.yml
See VULN-9916 for discussion, the list of configurations was also provided in that ticket. The intent is to exclude dependencies that are not bundled in the agent jar from the analysis.
> Exclude compile only dependencies from fossa analysis

- deployments/cloudfoundry/buildpack/manifest.yml
- deployments/cloudfoundry/index.yml
cflinuxcf3 is deprecated. 
https://community.sap.com/t5/technology-blogs-by-sap/deprecation-of-cloud-foundry-stack-cflinuxfs3-and-migration-to-cflinuxfs4/ba-p/13549149
> Update deprecated CF stack

- deployments/cloudfoundry/buildpack/README.md
Based on this comment:
https://github.com/cloudfoundry/cflinuxfs4-release/issues/2#issuecomment-1487651634
It's believed that this needs to be provided, otherwise the `supply` script (python) may not work. This is untested, but we had a report of cflinuxfs4 failing due to missing python.
> Add python buildpack

- CHANGELOG.md
- deployments/cloudfoundry/buildpack/README.md
- deployments/cloudfoundry/buildpack/bin/supply
I could not find a reasonable way to use python in the supply script, nor could I find any references that describe how to install python or any existing art that shows other buildpacks using python in `supply`.....so I think it's just easier to rewrite the thing in `bash` and eliminate the dependency entirely.
Also seems to be more consistent with other buildpacks.
> Remove python dependency for CloudFoundry supply

- CHANGELOG.md
- README.md
- deployments/cloudfoundry/buildpack/README.md
- version.gradle.kts
Patch release that includes the updated non-python cloudfoundry `supply` script.
> Prepare 1.30.3 release

- buildSrc/src/main/kotlin/splunk.shadow-conventions.gradle.kts
Update shading configuration to use the package where aws propagator currently is. As we get the aws propagator from upstream and don't include it ourself this change does not change anything, it only serves to align shading configuration with what the demo distro uses (there is pr with the same change in upstream).
> Update shading configuration

- metadata-generator/src/main/java/com/splunk/opentelemetry/tools/MetadataGenerator.java
The same metrics are also produced for other exporters e.g. zipkin, but I think we don't care about these.
> Add sdk otlp exporter metrics to metadata

- Dockerfile
- agent/build.gradle.kts
- scripts/release.sh
This cherry picks aaf480f27ae18d088bb18a21d016cb1f15293be3 from #1567 into the 1.32.x branch, so that the next release won't have the `-all` artifact, which is causing some confusion to some users.
> Skip publishing splunk-otel-javaagent-all.jar

- .github/workflows/gradle-wrapper-validation.yml
The release notes call this out:
https://github.com/gradle/wrapper-validation-action/releases/tag/v3.3.0
> Update the use of gradle wrapper validation to the current form.

- custom/build.gradle.kts
- custom/src/test/java/com/splunk/opentelemetry/TruncateCommandLineWhenMetricsEnabledTest.java
Looks like this dep was only used in 1 test and was just a silly string join that is easily accomplished in an alternative fashion.
> Remove commons lang

- smoke-tests/build.gradle.kts
`develocity.testRetry` is apparently the replacement.
> retry was deprecated

- CHANGELOG.md
- README.md
- deployments/cloudfoundry/buildpack/README.md
- version.gradle.kts
~~Please hold on the release until we are certain we can proceed. Thanks.~~ 
We will release `2.4.0-alpha` and drop alpha with 2.5.0. This PR has been updated to reflect that.
> Prepare for 2.4.0-alpha release

- build.gradle.kts
NOTE: This is for the `main` branch.
Seems like a good time to do this, given the change to sonatype token.
> Make environment vars consistent with upstream

- smoke-tests/src/test/resources/otel.yaml
Resolves https://github.com/signalfx/splunk-otel-java/issues/1922
Resolves https://github.com/signalfx/splunk-otel-java/issues/1924
by default collector now binds only to localhost
> Fix smoke test collector conf

- custom/src/main/java/com/splunk/opentelemetry/EndpointProtocolValidator.java
- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- custom/src/test/java/com/splunk/opentelemetry/EndpointProtocolValidatorTest.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkConfigurationTest.java
Warn when the port number in OTLP endpoint doesn't agree with configured protocol. Hopefully this will help users more easily diagnose issues caused by changing the default protocol to `http/protobuf`.
> Warn on potentially wrong endpoint configuration

- deployments/cloudfoundry/buildpack/README.md
When running the example command given, an error is returned. The command is successful without the `--enable` option. I assume it's been removed in a more recent version of `cf`.
```
$ cf create-buildpack splunk_otel_java_buildpack splunk_otel_java_buildpack-linux.zip 99 --enable
Incorrect Usage: unknown flag `enable'
NAME:
create-buildpack - Create a buildpack
USAGE:
cf create-buildpack BUILDPACK PATH POSITION [--disable]
TIP:
Path should be a zip file, a url to a zip file, or a local directory. Position is a positive integer, sets priority, and is sorted from lowest to highest.
OPTIONS:
--disable      Disable the buildpack from being used for staging
SEE ALSO:
buildpacks, push
$ cf version
cf version 8.7.8+515cf4e.2024-02-08
```
> [chore][deployments/cloudfoundry/buildpack] Fix example cf command

- README.md
- dependencyManagement/build.gradle.kts
- deployments/cloudfoundry/index.yml
- licenses/licenses.md
- version.gradle.kts
> v2.8.0 post release changes

- dependencyManagement/build.gradle.kts
Currently because we set the semconv version we get renovate updates for it that we don't want (can't update semconv anyway before upstream updates).
> Let opentelemetry instrumentation bom configure the semconv version

- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogExporterBuilderTest.java
Use `otel.exporter.otlp.protocol` when `splunk.profiler.otlp.protocol` is not set.
> Allow setting otlp protocol for profiler with otel.exporter.otlp.protocol

- buildSrc/src/main/kotlin/splunk.spotless-conventions.gradle.kts
`indentWithSpaces()` function was deprecated in spotless and is replaced with `leadingTabsToSpaces()`
> Spotless rules update

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- custom/build.gradle.kts
- custom/src/main/java/com/splunk/opentelemetry/SplunkDistroVersionResourceProvider.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkDistroVersionResourceProviderTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
> Adopt GDI spec 1.7.0

- custom/src/test/java/com/splunk/opentelemetry/TruncateCommandLineWhenMetricsEnabledTest.java
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/2177
`ResourceAttributes` class does not exist after semconv version was updated in the upstream
> Fix import after semconv update

- profiler/src/main/java/com/splunk/opentelemetry/profiler/InstrumentationSource.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/ProfilingSemanticAttributes.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/allocation/exporter/PprofAllocationEventExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/exporter/PprofCpuEventExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/exporter/PprofLogDataExporter.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/InstrumentationSourceTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/exporter/InMemoryOtelLogger.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/exporter/PprofLogDataExporterTest.java
Adding an instrumentation source attribute to exported profiling logs. This new attribute will be utilized by the profiling log ingestion pipeline to differentiate between the existing continuous callstacks and the upcoming trace snapshot callstacks.
> Profiling instrumentation source

- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/ProbabilisticSnapshotSelectorTest.java
https://scans.gradle.com/s/n6ltz4zeeihpc/tests/task/:profiler:test/details/com.splunk.opentelemetry.profiler.snapshot.ProbabilisticSnapshotSelectorTest/evaluateOutliers()?expanded-stacktrace=WyIwIl0&top-execution=1
cc @tduncan
> Disable flaky test

- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/windows/WindowsTestContainerManager.java
Hopefully gets rid of
> 05:52:22.276 [docker-java-stream-1326425793] ERROR c.s.o.h.w.WindowsTestContainerManager - STDERR: 2025-02-27T05:52:22.276Z	info	internal/retry_sender.go:126	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "splunk_hec", "error": "Post \"http://hec-backend:1080/services/collector/event\": dial tcp: lookup hec-backend: no such host", "interval": "3.147414794s"}
> Disable logs exporter for windows smoke tests

- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/AbstractTestContainerManager.java
resolves https://github.com/signalfx/splunk-otel-java/issues/2211
hopefully with this we'll know whether the span was exported from the agent at all next time we have a similar failure
> Enable console exporter for traces in smoke tests

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/SnapshotProfilingSdkCustomizer.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/SnapshotVolumePropagatorProvider.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/AutoConfigureSnapshotVolumePropagatorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/OpenTelemetrySdkExtension.java
This PR attempts to modify the `otel.propagators` value to autoconfigure the recently added `SnapshotVolumePropagatorProvider` as well as ensure the propagator is invoked after both the W3C baggage and trace context propagators.
> Autoconfigure Snapshot Volume Propagator

- profiler/src/test/java/com/splunk/opentelemetry/profiler/exporter/InMemoryOtelLogger.java
Move `@SuppressWarnings(deprecation)` from inner class to outer class since there is one more usage of the deprecated type in the outer class.
> Move @SuppressWarnings(deprecation)

- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/nocode/NocodeEvaluation.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/nocode/NocodeRules.java
- instrumentation/nocode/README.md
- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/JexlEvaluator.java
- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/NocodeAttributesExtractor.java
- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/NocodeInstrumentation.java
- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/NocodeSingletons.java
- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/NocodeSpanStatusExtractor.java
- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/YamlParser.java
- instrumentation/nocode/src/test/config/nocode.yml
- instrumentation/nocode/src/test/java/com/splunk/opentelemetry/instrumentation/nocode/NocodeInstrumentationTest.java
Adds the ability to set `spanStatus` via nocode expressions like
```
spanStatus: 'returnValue.statusCode() > 3 ? "OK" : "ERROR"'
```
Adds a barebones `README.md` to document some basic behavior.
> Add ability to set span status through nocode expressions

- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogExporterBuilder.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogExporterBuilderTest.java
This was a user request. They expect the profiling logs exporter to behave consistently with the other signals.
Seems like a reasonable ask, especially until/before we have native profiles ingest available.
> Pass through configured otlp headers for logs containing profiles.

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/ScheduledExecutorStackTraceSampler.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/InMemoryStagingArea.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/ScheduledExecutorStackTraceSamplerTest.java
Use a scheduler to stagger the simulated concurrent start span operations in the test that verifies only a single thread is profiled at a time.
> Fix Flaky Test

- custom/src/main/java/com/splunk/opentelemetry/appd/AppdBonusSpanProcessor.java
- custom/src/test/java/com/splunk/opentelemetry/appd/AppdBonusCustomizerTest.java
- custom/src/test/java/com/splunk/opentelemetry/appd/AppdBonusSpanProcessorTest.java
As mentioned in https://github.com/signalfx/gdi-specification/pull/338, 4 AppD context headers should be transferred into corresponding span attributes only for the root span.
Related to https://github.com/signalfx/splunk-otel-java/pull/2198
> Only root span gets AppD attributes set

- smoke-tests/src/test/java/com/splunk/opentelemetry/ProfilerSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SnapshotProfilerSmokeTest.java
Copied from the existing profiler smoke test. cc @tduncan
> Add smoke test for snapshot profiler

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/TraceRegistry.java
This PR modifies `TraceRegistry` to use a `Set` instead of a `Map`. As noted by @laurit [here](https://github.com/signalfx/splunk-otel-java/pull/2251#discussion_r2024952775) only the keys of the `Map` are used.
> Update TraceRegistry To Use A Set

- profiler/build.gradle.kts
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/ActiveSpanTrackerTest.java
https://scans.gradle.com/s/e4obj6xipjjxu/tests/task/:profiler:test/details/com.splunk.opentelemetry.profiler.snapshot.ActiveSpanTrackerTest/automaticallyRemoveUnclosedScopesAfterTheirReferencesExpire()?expanded-stacktrace=WyIwIl0&top-execution=1
cc @tduncan
> Hopefully fix flaky profiler test

- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ConfigurationTest.java
Lowering the default snapshot interval to 10ms to align with the default behavior of the AppDynamics agents.
> Decrease the trace profiling snapshot interval to 10ms.

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/ScheduledExecutorStackTraceSampler.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/ScheduledExecutorStackTraceSamplerTest.java
This PR closes a bug that could cause the snapshot profiling of a trace to be stopped before the thread being profiled has actually stopped processing that trace. This is possible when multiple API calls are made to a service simultaneously the a thread that did not start the profiling is the first thread to finish processing its request.
> Only Stop Trace Profiling When Same Span Ends

- agent-csa-bundle/README.md
- agent-csa-bundle/build-agent-csa-fat-jar.sh
- agent-csa-bundle/build.gradle.kts
- agent-csa-bundle/otel-extension-system.properties
- settings.gradle.kts
This adds a module that will publish a second jar file that contains the Cisco Secure Application extension bundled inside `splunk-otel-java`. The output jar is named `splunk-otel-javaagent-csa-<version>.jar`.
> Publish CSA bundle

- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/ScheduledExecutorStackTraceSamplerTest.java
This PR fixes an unreliable test recently introduced in `ScheduledExecutorStackTraceSamplerTest`. The test relied on a specific span to start the trace profiling.
> Fix Flaky test in ScheduledExecutorStackTraceSamplerTest

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/AsyncStackTraceExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/ScheduledExecutorStackTraceSampler.java
This PR updates the `ExecutorService` and `ScheduledExecutorService` instances in the trace snapshot profiler to use implementations that create daemon threads.
> Use Daemon Threads In Trace Snapshot Profiler

- instrumentation/nocode/README.md
Fix a few syntax typos in the nocode docs and add a stern warning that you should know what you're doing or things will break.
> nocode docs: fix typos and add stern warning

- .gitlab-ci.yml
- scripts/publish-docker-image.sh
Automatic signing docker images published on quay.io during the release process.
Procedure is described [here](https://cd.splunkdev.com/cloud-automation/ci-cd/artifactory/artifact-ci#sign-docker)
> Signing docker images published on quay.io

- agent-csa-bundle/build.gradle.kts
After #2287 was merged, the snapshot builds in _gitlab_ began failing due to 
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':agent-csa-bundle'.
> Cannot change hierarchy of dependency configuration ':agent-csa-bundle:csaReleases' after it has been resolved.
```
Obviously a very clear and helpful error message. 🙄 
Especially weird that the exact same gradle command passes both locally on my box but also in GitHub. Feh.
Anyway, I found some prior art that this kind of problem is caused by stuff being done at config time. Because it's complaining about the `csReleases` config, and the config is only mentioned in 3 places (the declaration of the config itself, once in the dependency block, and the `zipTree()` copy [as changed in this …
> Attempt to fix gitlab build

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/AccumulatingStagingArea.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/AsyncStackTraceExporter.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/StackTraceExporter.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/InMemoryStackTraceExporter.java
Stores staged `StackTrace` instances in a thread-safe `Queue` while exporting a "view" of that `Queue` when `empty` is called.
> Make AccumulatingStagingArea Thread Safe

- agent-csa-bundle/otel-extension-system.properties
Just a new version of the props file to bundle.
> Update csa bundle properties file

- build.gradle.kts
See this annoucement: https://central.sonatype.org/news/20250326_ossrh_sunset/
and see this for the docs on this change https://github.com/gradle-nexus/publish-plugin?tab=readme-ov-file#publishing-to-maven-central-via-sonatype-central
Once a new token is generated and put into GitLab releaser repo, we can merge this to get the new urls into place.
> Update repos for sonatype central

- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/NocodeInitializer.java
- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/YamlParser.java
```
05:51:25.462 [docker-java-stream--1691006325] ERROR c.s.o.h.w.WindowsTestContainerManager - STDERR: [otel.javaagent 2025-06-05 05:51:25:461 +0000] [main] ERROR com.splunk.opentelemetry.instrumentation.nocode.NocodeInitializer - Can't load configured nocode yaml. |  
-- | --
  | 05:51:25.464 [docker-java-stream--1691006325] ERROR c.s.o.h.w.WindowsTestContainerManager - STDERR: java.lang.NullPointerException |  
  | 05:51:25.465 [docker-java-stream--1691006325] ERROR c.s.o.h.w.WindowsTestContainerManager - STDERR: 	at com.splunk.opentelemetry.instrumentation.nocode.YamlParser.parseFromFile(YamlParser.java:51) |  
  | 05:51:25.466 [docker-java-stream--1691006325] ERROR c.s.o.h.w.WindowsTestContainerManager - STDERR: 	at com.splunk.opentelemetry.instrumentation.nocode.NocodeInitializer.bef …
```
> Avoid NPE when nocode configuration file is not set

- instrumentation/nocode/src/main/java/com/splunk/opentelemetry/instrumentation/nocode/NocodeInstrumentation.java
The advice code does not work for constructors. Explicitly restrict the matching to methods in case other rules allow matching a constructor.
> Restrict nocode instrumentation to methods

- README.md
Remove the deprecation notice at the top of the readme. 1.x is no longer supported.
> 1.x reached end of support

- .github/workflows/ci.yaml
- .github/workflows/nightly.yaml
- .github/workflows/pr.yaml
- .lychee.toml
- CONTRIBUTING.md
... and add splunk quickdraw docs redirector as an exclude.
The quickdraw redirector is currently giving 403s and causing our jobs to fail.
> consolidate the lychee config under one roof

- README.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/2429
Resolves https://github.com/signalfx/splunk-otel-java/issues/2426
`maven-badges.herokuapp.com` currently fails the link check with 403. In addition it redirects to `search.maven.org` that doesn't currently list the latest agent jar. Lets just link to https://central.sonatype.com/artifact/com.splunk/splunk-otel-javaagent
> Fix maven central link

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/SnapshotProfilingConfiguration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/SnapshotVolumePropagatorProvider.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/TraceIdBasedSnapshotSelector.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/SnapshotProfilingConfigurationTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/SnapshotVolumePropagatorProviderTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SnapshotProfilerSmokeTest.java
This is simply a cosmetic rename of the term `rate`, which I think is too suggestive of time. I thought the term `probability` was more fitting here -- as it's the chance of something happening.
> Rename `rate` to `probability` for snapshotting

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/SnapshotProfilingConfiguration.java
There have been multiple times in the last couple weeks where I went to verify a configuration setting and couldn't find it by searching due to the PREFIX being split out. While I understand that this can possibly reduce a certain class of error and reduces repetition, I think it makes the code less readable and absolutely less searchable....so this joins them back.
I also missed a few changes of the word "rate" and picked those up here into "probability".
> Join the string constants for snapshot config

- profiler/src/main/java/com/splunk/opentelemetry/profiler/snapshot/ContextStorageWrapper.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/ContextStorageWrapperTest.java
This PR swaps the order in which the two `ContextStorage` wrappers run so that an active span will be available to the `StackTraceSampler` when the first on demand sample is taken.
> Re-order ContextStorage Wrappers

- .gitlab-ci.yml
* fix incorrect ref name
* address warning in build output:
```
==============================================================
[WARNING] This is NOT the official SAST template!
Using this template may lead to inaccurate scan results.
Please include the official template in your pipeline as shown below:
- project: 'ci-cd/templates'
file: '/prodsec/.sast-scan.yml'
==============================================================
```
> Update GitLab templates
