- deployments/cloudfoundry/buildpack/README.md
- deployments/cloudfoundry/buildpack/bin/detect
- deployments/cloudfoundry/buildpack/bin/finalize
- deployments/cloudfoundry/buildpack/bin/supply
- deployments/cloudfoundry/buildpack/manifest.yml
- index.yml
`index.yml` is no longer needed in this case, removing it together with the issue that I created.
> Add CloudFoundry buildpack

- migration.md
- Add new H2 section to capture changes in functionality as a result of the migration
- Add H3 section about changes to the @Trace annotation
> Migration info for trace annotation changes

- migration.md
- Add section about how log injection changes with the migration
> Migration info about log injection changes

- .github/workflows/snapshot.yaml
- build.gradle
No automatic issue creation for now, because until GA lots of breaking changes are expected.
> Introduce nightly build with upstream snapshot

- README.md
- update supported otel version and API version for 0.5.0
> update compatible otel version and API version

- build.gradle
- instrumentation/glassfish/src/main/java/com/splunk/opentelemetry/middleware/GlassfishAttributesInstrumentationModule.java
- instrumentation/jetty/src/main/java/com/splunk/opentelemetry/middleware/JettyAttributesInstrumentationModule.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/middleware/LibertyAttributesInstrumentationModule.java
- instrumentation/tomcat/src/main/java/com/splunk/opentelemetry/middleware/TomcatAttributesInstrumentationModule.java
- instrumentation/wildfly/src/main/java/com/splunk/opentelemetry/middleware/WildFlyAttributesInstrumentationModule.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JBossEapSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/LibertySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomcatSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WildFlySmokeTest.java
0.14 has some incompatible changes because of moved classes. Still waiting for 0.14 from instrumentation, though.
> Update otel-java and otel-java-instrumentation to 0.14

- README.md
- custom/src/main/java/com/splunk/opentelemetry/jaeger/JaegerThriftSpanExporterFactory.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TraceInspector.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/AbstractTestContainerManager.java
And add a smoke test that verifies that otel resource works correctly
Related to https://github.com/signalfx/splunk-otel-java/discussions/114
> Fix README regarding setting service name

- .github/no-response.yaml
- .github/release-drafter.yaml
- .github/stale.yaml
* Enable auto-close of issues with no response from issue author
* Enable auto-close of stale issues
* Enable release notes to be automatically drafted
> Configure bots

- agent/build.gradle
- custom/build.gradle
- gradle/instrumentation.gradle
- gradle/shadow.gradle
- instrumentation/build.gradle
Resolves https://github.com/signalfx/splunk-otel-java/issues/48
> Remove copy-pasted shadow jar relocations

- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/commonsdbcp2/CommonsDbcp2InstrumentationModule.java
- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/commonsdbcp2/DataSourceMetrics.java
- instrumentation/commons-dbcp2/src/test/java/com/splunk/opentelemetry/commonsdbcp2/CommonsDbcp2InstrumentationTest.java
- testing/agent-metrics/src/main/java/com/splunk/opentelemetry/testing/TestMetrics.java
- testing/common/src/main/java/com/splunk/opentelemetry/testing/TestMetricsAccess.java
See https://github.com/signalfx/splunk-otel-java/pull/144#discussion_r604700266
> Unregister DBCP2 metrics when removed from JMX

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- smoke-tests/build.gradle
Similar to how it's done in the upstream repo
> Split smoke tests into several suites

- build.gradle
- custom/build.gradle
- gradle/dependencies.gradle
- gradle/instrumentation.gradle
- instrumentation/commons-dbcp2/build.gradle
- smoke-tests/build.gradle
- testing/agent-metrics/build.gradle
Introduce a common dependencies.gradle file
> Gradle dependencies refactor

- README.md
- RELEASING.md
- deployments/cloudfoundry/buildpack/README.md
- docs/advanced-config.md
- docs/correlating-traces-with-logs.md
- docs/middleware-attributes.md
- docs/supported-libraries.md
- docs/troubleshooting.md
* Add fancy links and a new badge to the top of the README
* Document sending directly to Splunk ingest
> Make the README a bit slimmer

- docs/advanced-config.md
- docs/metrics.md
- docs/supported-libraries.md
- docs/troubleshooting.md
❗ DO NOT MERGE BEFORE 0.10.0 RELEASE ❗
> [DO NOT MERGE] Document Micrometer metrics

- docs/advanced-config.md
- docs/server-trace-info.md
❗ DO NOT MERGE BEFORE 0.10.0 RELEASE ❗
> SPLUNK_TRACE_RESPONSE_HEADER_ENABLED documentation changes

- VERSIONING.md
First sketch of versioning strategy.
Maintainers - please have a look.
> Versioning strategy

- .github/workflows/ci.yaml
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
> Disable docker login step

- CHANGELOG.md
- custom/build.gradle
- gradle/dependencies.gradle
- gradle/instrumentation.gradle
- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/commonsdbcp2/CommonsDbcp2InstrumentationModule.java
- instrumentation/glassfish/src/main/java/com/splunk/opentelemetry/middleware/GlassfishAttributesInstrumentationModule.java
- instrumentation/jetty/src/main/java/com/splunk/opentelemetry/middleware/JettyAttributesInstrumentationModule.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/middleware/LibertyAttributesInstrumentationModule.java
- instrumentation/netty-3.8/src/main/java/com/splunk/opentelemetry/netty/v3_8/ChannelPipelineInstrumentation.java
- instrumentation/netty-3.8/src/main/java/com/splunk/opentelemetry/netty/v3_8/NettyInstrumentationModule.java
- instrumentation/netty-4.0/src/main/java/com/splunk/opentelemetry/netty/v4_0/ChannelPipelineInstrumentation.java
- instrumentation/netty-4.0/src/main/java/com/splunk/opentelemetry/netty/v4_0/NettyInstrumentationModule.java
- instrumentation/servlet/src/main/java/com/splunk/opentelemetry/servlet/ServletInstrumentationModule.java
- instrumentation/tomcat/src/main/java/com/splunk/opentelemetry/middleware/TomcatAttributesInstrumentationModule.java
- instrumentation/tomee/src/main/java/com/splunk/opentelemetry/middleware/TomeeAttributesInstrumentationModule.java
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/middleware/weblogic/WebLogicInstrumentationModule.java
- instrumentation/wildfly/src/main/java/com/splunk/opentelemetry/middleware/WildFlyAttributesInstrumentationModule.java
- testing/agent-metrics/build.gradle
> Update to upstream 1.2.0

- MIGRATING.md
- README.md
- docs/advanced-config.md
- docs/troubleshooting.md
This PR will be merged just before the 0.11.0 release, please do not merge it earlier. You're welcome to review it as early as you can though.
> Update documentation according to GDI spec

- .gitlab-ci.yml
- deployments/cloudfoundry/buildpack/build.sh
Fixes https://github.com/signalfx/splunk-otel-java/issues/54
> Attach buildpack zip during release process

- docs/advanced-config.md
- docs/metrics.md
* Add supported library versions to metrics doc
* Add Support=Stable column to all config options that did not have it
in advanced-config.md
> One more docs update after GDI spec review

- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
Closes https://github.com/signalfx/splunk-otel-java/issues/206
> Silence confusing signalfx metrics exporter INFO log

- .gitignore
- README.md
- deployments/cloudfoundry/buildpack/README.md
- post-release.sh
- pre-release.sh
Those pre- and post-release scripts should help with updating READMEs in this repo.
TODO: CHANGELOG.md
> Add pre- and post-release helper scripts for updating versions

- profiler/build.gradle
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrRecorder.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingEscapeHatch.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingSequencer.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingStartPredicate.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/util/HelpfulExecutors.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/RecordingSequencerTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/util/HelpfulExecutorsTest.java
This sequencer will periodically and conditionally flush recording data to disk.  The predicate and recorder are simply stubbed for now and will be fleshed out in subsequent/following PRs.
> Add a profile recording sequencer.

- custom/src/main/java/com/splunk/opentelemetry/ServiceNameChecker.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstaller.java
- custom/src/main/java/com/splunk/opentelemetry/resource/ResourceAttributesToSystemProperties.java
- gradle/dependencies.gradle
- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/commonsdbcp2/CommonsDbcp2InstrumentationModule.java
- instrumentation/glassfish/src/main/java/com/splunk/opentelemetry/middleware/GlassfishAttributesInstrumentationModule.java
- instrumentation/jetty/src/main/java/com/splunk/opentelemetry/middleware/JettyAttributesInstrumentationModule.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/jvmmetrics/JvmMetricsInstaller.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/middleware/LibertyAttributesInstrumentationModule.java
- instrumentation/netty-3.8/src/main/java/com/splunk/opentelemetry/netty/v3_8/ChannelPipelineInstrumentation.java
- instrumentation/netty-3.8/src/main/java/com/splunk/opentelemetry/netty/v3_8/NettyInstrumentationModule.java
- instrumentation/netty-3.8/src/test/java/com/splunk/opentelemetry/netty/v3_8/NettyInstrumentationTest.java
- instrumentation/netty-4.0/src/main/java/com/splunk/opentelemetry/netty/v4_0/ChannelPipelineInstrumentation.java
- instrumentation/netty-4.0/src/main/java/com/splunk/opentelemetry/netty/v4_0/NettyInstrumentationModule.java
- instrumentation/netty-4.0/src/test/java/com/splunk/opentelemetry/netty/v4_0/NettyInstrumentationTest.java
- instrumentation/servlet-3-testing/src/test/java/com/splunk/opentelemetry/servlet/Servlet3InstrumentationTest.java
- instrumentation/servlet/src/main/java/com/splunk/opentelemetry/servlet/ServletInstrumentationModule.java
- instrumentation/servlet/src/test/java/com/splunk/opentelemetry/servlet/ServletInstrumentationTest.java
- instrumentation/tomcat/src/main/java/com/splunk/opentelemetry/middleware/TomcatAttributesInstrumentationModule.java
- instrumentation/tomee/src/main/java/com/splunk/opentelemetry/middleware/TomeeAttributesInstrumentationModule.java
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/middleware/weblogic/WebLogicInstrumentationModule.java
- instrumentation/wildfly/src/main/java/com/splunk/opentelemetry/middleware/WildFlyAttributesInstrumentationModule.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/LinuxTestContainerManager.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/windows/WindowsTestContainerManager.java
- testing/agent-metrics/src/main/java/com/splunk/opentelemetry/testing/TestMicrometerInstaller.java
- testing/common/build.gradle
I wanted to migrate khttp instrumentation that was removed from upstream. But for that I need latest upstream.
> Preparing for upstream version upgrade

- CHANGELOG.md
- README.md
- deployments/cloudfoundry/buildpack/README.md
Also update changelog so that it's correct this time
> 1.1.0 pre-release changes 

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
Added to the main CI but also for PRs.
> Let's add the profiler smoke test to catch regressions.

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
Resolves #267 
More closely matches the otel specs for durations/periods (link in #267).
> change recording duration to ms

- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/CounterSemanticConvention.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/DataSourceSemanticConventions.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/GaugeSemanticConvention.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/GlobalMetricsTags.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/TimerSemanticConvention.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstaller.java
- docs/metrics.md
- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/commonsdbcp2/BasicDataSourceInstrumentation.java
- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/commonsdbcp2/DataSourceMetrics.java
- instrumentation/hikaricp/build.gradle.kts
- instrumentation/hikaricp/src/main/java/com/splunk/opentelemetry/hikaricp/HikariDataSourceInstrumentation.java
- instrumentation/hikaricp/src/main/java/com/splunk/opentelemetry/hikaricp/HikariInstrumentationModule.java
- instrumentation/hikaricp/src/main/java/com/splunk/opentelemetry/hikaricp/HikariPoolInstrumentation.java
- instrumentation/hikaricp/src/main/java/com/splunk/opentelemetry/hikaricp/MicrometerMetricsTracker.java
- instrumentation/hikaricp/src/main/java/com/splunk/opentelemetry/hikaricp/MicrometerMetricsTrackerFactory.java
- instrumentation/hikaricp/src/test/java/com/splunk/opentelemetry/hikaricp/HikariInstrumentationTest.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/jvmmetrics/JvmMetricsInstaller.java
- settings.gradle.kts
- testing/common/src/main/java/com/splunk/opentelemetry/testing/MeterData.java
Plus some refactorings to share common names/conventions between connection pool instrumentations
> Implement metrics for Hikari connection pool

- README.md
Update README according to @theletterf's suggestion.
> Update README after merge

- docs/metrics.md
> Minor fix to metrics.md doc

- docs/metrics.md
- instrumentation/vibur-dbcp/build.gradle.kts
- instrumentation/vibur-dbcp/src/main/java/com/splunk/opentelemetry/viburdbcp/ConnectionPoolMetrics.java
- instrumentation/vibur-dbcp/src/main/java/com/splunk/opentelemetry/viburdbcp/ViburDbcpDataSourceInstrumentation.java
- instrumentation/vibur-dbcp/src/main/java/com/splunk/opentelemetry/viburdbcp/ViburDbcpInstrumentationModule.java
- instrumentation/vibur-dbcp/src/test/java/com/splunk/opentelemetry/viburdbcp/ViburDbcpInstrumentationTest.java
- settings.gradle.kts
CC @theletterf - there are some minor docs changes.
> Implement connection pool metrics for Vibur DBCP

- agent/build.gradle.kts
- buildSrc/src/main/kotlin/splunk.shadow-conventions.gradle.kts
- instrumentation/build.gradle.kts
- instrumentation/micrometer-shaded-for-instrumenting/build.gradle.kts
- instrumentation/micrometer/build.gradle.kts
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationClock.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationCounter.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationDistributionSummary.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationFunctionCounter.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationFunctionTimer.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationGauge.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationLongTaskTimer.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationMeter.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationMeterRegistry.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/ApplicationTimer.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/Bridging.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/MetricsInstrumentation.java
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstrumentationModule.java
- instrumentation/micrometer/src/test/java/com/splunk/opentelemetry/micrometer/MicrometerBridgeTest.java
- settings.gradle.kts
- testing/agent-test-extension/src/main/java/com/splunk/opentelemetry/testing/TestMetrics.java
- testing/common/src/main/java/com/splunk/opentelemetry/testing/MeterData.java
- testing/common/src/main/java/com/splunk/opentelemetry/testing/TestMetricsAccess.java
Part 1 - I left a couple of TODOs that'll be resolved in next PR(s)
> Implement application<->agent Micrometer bridge

- README.md
I've wanted this link in here more than once, so it's kind of self-serving...but maybe this also is enough to satisfy #391 ?
> Link to snapshot builds and provide a note.

- custom/src/main/java/com/splunk/opentelemetry/instrumentation/micrometer/SplunkMetricsConfig.java
- docs/advanced-config.md
- instrumentation/micrometer/src/main/java/com/splunk/opentelemetry/instrumentation/micrometer/ApplicationMeterRegistry.java
- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
Fixes https://github.com/signalfx/splunk-otel-java/issues/412
> Fix build; use the new Config#getDuration() method

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/Configuration.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/EventProcessingChain.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsOverrides.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogEntryCommonAttributes.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogEntryCreator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/StackToSpanLinkage.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/events/RelevantEvents.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/util/StackSerializer.java
- profiler/src/main/resources/jfr.settings
- profiler/src/test/java/com/splunk/opentelemetry/profiler/EventProcessingChainTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrSettingsOverridesTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogEntryCommonAttributesTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogEntryCreatorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/util/StackSerializerTest.java
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/profiler/ProfilerSmokeTest.java
- testing/profiler-tests/src/test/java/com/splunk/opentelemetry/profiler/TestHelpers.java
- testing/profiler-tests/src/test/resources/collector.yaml
Tracking allocations and the stacks for where they happen.
> Add profiler TLAB support.

- profiler/src/main/java/com/splunk/opentelemetry/profiler/ProfilingSemanticAttributes.java
> remove unused attributes

- CHANGELOG.md
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- custom/build.gradle.kts
- custom/src/main/java/com/splunk/opentelemetry/ServiceNameChecker.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/GlobalTagsBuilder.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerBootstrapPackagesProvider.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstaller.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/OtelNamingConvention.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfig.java
- custom/src/main/java/com/splunk/opentelemetry/resource/ResourceAttributesToSystemProperties.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/GlobalTagsBuilderTest.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/OtelNamingConventionTest.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfigTest.java
- instrumentation/common/src/main/java/com/splunk/opentelemetry/instrumentation/servertiming/ServerTimingHeader.java
- profiler/build.gradle.kts
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsOverrides.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogsExporterBuilder.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/SdkCustomizer.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/JfrSettingsOverridesTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogsExporterBuilderTest.java
- testing/agent-test-extension/src/main/java/com/splunk/opentelemetry/testing/TestMicrometerInstaller.java
In preparation for the next release
> Update upstream version to 1.5.0

- instrumentation/netty-3.8/src/main/java/com/splunk/opentelemetry/instrumentation/netty/v3_8/ServerTimingHandler.java
Fixes https://github.com/signalfx/splunk-otel-java/issues/451
Fixes https://github.com/signalfx/splunk-otel-java/issues/450
Fixes https://github.com/signalfx/splunk-otel-java/issues/449
> Fix compilation on the main branch

- docs/faq.md
@theletterf Could you review :)
> Add FAQ entry for exporter failure

- profiler/build.gradle.kts
Fixes https://github.com/signalfx/splunk-otel-java/issues/459
> Fix CI build

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- buildSrc/src/main/kotlin/splunk.muzzle-conventions.gradle.kts
> Add muzzle dependency

- docs/server-instructions.md
Fix glassfish/payara (there was some weird space) and add a table of contents.
> Enhancements to server instructions

- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/SpanContextualizer.java
The SpanContextualizer was dong a `split()` on every stack it encountered. This was used only to determine if the stack was actually multi line (with the first line being meta). Because the `StackDescriptorLineParser` happily handles the full stack string for its input, we can omit the expensive `split()` call and just use `indexOf()` to determine if we have multiple lines. 
This should ultimately avoid some allocations.
> Remove expensive split() from contextualizer

- profiler/README.md
This builds out more of the README body for the profiler and adds a troubleshooting faq.
> Profiler readme enhancements

- agent/build.gradle.kts
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
Fixes #482 
Fixes #483 
Fixes #484
> Fix main build

- README.md
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- instrumentation/micrometer/build.gradle.kts
- scripts/post-release.sh
I forgot to do this last week; and then the CI has been failing for a while and I couldn't update the muzzle plugins' version.
> Post 1.5.0 changes

- profiler/README.md
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JFR.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
resolves #476 
"Java Flight Recorder" -> "JDK Flight Recorder"
> JFR acronym

- docs/server-instructions.md
> Add configuration instructions for websphere

- smoke-tests/src/test/java/com/splunk/opentelemetry/LibertySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WebSphereSmokeTest.java
Liberty tests occasionally time out on windows hopefully this fill help.
> Add wait strategy for websphere and liberty smoke tests

- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsOverrides.java
- profiler/src/main/resources/jfr.settings
Decreasing based on COGS estimates pre GA.
> Change default thread dump rate

- instrumentation/c3p0/build.gradle.kts
- instrumentation/c3p0/src/main/java/com/splunk/opentelemetry/instrumentation/c3p0/C3p0InstrumentationModule.java
- instrumentation/common/build.gradle.kts
- instrumentation/common/src/main/java/com/splunk/opentelemetry/instrumentation/MetricsDependentInstrumentationModule.java
- instrumentation/common/src/main/java/com/splunk/opentelemetry/instrumentation/MetricsInstrumentationModule.java
- instrumentation/commons-dbcp2/build.gradle.kts
- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/instrumentation/commonsdbcp2/CommonsDbcp2InstrumentationModule.java
- instrumentation/hikaricp/build.gradle.kts
- instrumentation/hikaricp/src/main/java/com/splunk/opentelemetry/instrumentation/hikaricp/HikariInstrumentationModule.java
- instrumentation/liberty/build.gradle.kts
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/instrumentation/liberty/metrics/LibertyMetricsInstrumentationModule.java
- instrumentation/micrometer-1.3/build.gradle.kts
- instrumentation/micrometer-1.3/src/main/java/com/splunk/opentelemetry/instrumentation/micrometer/v1_3/MicrometerInstrumentationModule.java
- instrumentation/micrometer-1.5/build.gradle.kts
- instrumentation/micrometer-1.5/src/main/java/com/splunk/opentelemetry/instrumentation/micrometer/v1_5/MicrometerInstrumentationModule.java
- instrumentation/oracle-ucp/build.gradle.kts
- instrumentation/oracle-ucp/src/main/java/com/splunk/opentelemetry/instrumentation/oracleucp/OracleUcpInstrumentationModule.java
- instrumentation/tomcat-jdbc/build.gradle.kts
- instrumentation/tomcat-jdbc/src/main/java/com/splunk/opentelemetry/instrumentation/tomcatjdbc/TomcatJdbcInstrumentationModule.java
- instrumentation/tomcat/build.gradle.kts
- instrumentation/tomcat/src/main/java/com/splunk/opentelemetry/instrumentation/tomcat/metrics/TomcatMetricsInstrumentationModule.java
- instrumentation/vibur-dbcp/build.gradle.kts
- instrumentation/vibur-dbcp/src/main/java/com/splunk/opentelemetry/instrumentation/viburdbcp/ViburDbcpInstrumentationModule.java
- instrumentation/weblogic/build.gradle.kts
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/instrumentation/weblogic/metrics/WebLogicMetricsInstrumentationModule.java
I'm torn -- on the one hand we keep seeing this pattern repeat itself and this is a cheesy way to button up some of that duplication...but on the other hand it makes me pretty uncomfortable to add another class to the inheritance tree.
Curious what others think. Good idea or just leave well enough alone?
> introduce MetricsDependentInstrumentationModule

- buildSrc/src/main/kotlin/splunk.instrumentation-conventions.gradle.kts
- custom/build.gradle.kts
- custom/src/main/java/com/splunk/opentelemetry/ServiceNameChecker.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstaller.java
- custom/src/main/java/com/splunk/opentelemetry/resource/ResourceAttributesToSystemProperties.java
- custom/src/test/java/com/splunk/opentelemetry/ServiceNameCheckerTest.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsInstaller.java
- profiler/build.gradle.kts
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogsExporterBuilder.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogsExporterBuilderTest.java
- testing/agent-test-extension/build.gradle.kts
- testing/agent-test-extension/src/main/java/com/splunk/opentelemetry/testing/TestMicrometerInstaller.java
Supersedes https://github.com/signalfx/splunk-otel-java/pull/554
> Don't use deprecated AgentListener methods

- profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java
- profiler/src/test/java/com/splunk/opentelemetry/logs/OtlpLogsExporterTest.java
> [profiler] Log export errors at most once per hour

- instrumentation/micrometer-1.3/src/main/java/com/splunk/opentelemetry/instrumentation/micrometer/v1_3/MicrometerInstrumentationModule.java
- instrumentation/micrometer-1.5/src/main/java/com/splunk/opentelemetry/instrumentation/micrometer/v1_5/MicrometerInstrumentationModule.java
... so that it does not clash with the upstream one I've just started working on.
> Change the instrumentation name of the micrometer instrumentation

- MIGRATING.md
- README.md
- deployments/cloudfoundry/buildpack/bin/supply
`splunk-otel-javaagent.jar` and `splunk-otel-javaagent-all.jar` are the same.
> Remove javaagent-all

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- profiler/src/main/java/com/splunk/opentelemetry/profiler/EventProcessingChain.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrContextStorage.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/SpanContextualizer.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/context/SpanLinkage.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/EventProcessingChainTest.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/TLABProcessorTest.java
- smoke-tests/build.gradle.kts
- smoke-tests/src/test/java/com/splunk/opentelemetry/LogsInspector.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/ProfilerTlabSanityTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TelemetryRetriever.java
- smoke-tests/src/test/resources/otel.yaml
- smoke-tests/src/test/resources/tlab-sanity-test-app/TlabSanityTestApp.java
- smoke-tests/src/test/resources/tlab-sanity-test-app/start.sh
> Sanity check TLAB stacks for span linkage

- smoke-tests/src/test/java/com/splunk/opentelemetry/ProfilerSmokeTest.java
> Fix ProfilerSmokeTest

- CHANGELOG.md
- README.md
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- deployments/cloudfoundry/buildpack/README.md
Patch release based on the upstream 1.10.1 patch
> v1.7.2 pre release changes

- profiler/src/main/java/com/splunk/opentelemetry/profiler/RecordingSequencer.java
As far as I understand recordings don't really overlap.
> Remove overlap factor

- custom/build.gradle.kts
- custom/src/main/java/com/splunk/opentelemetry/micrometer/CustomSignalFxConfig.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/CustomSignalFxMeterRegistry.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstaller.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfig.java
Copy micrometer signalfx registry with fixes from https://github.com/micrometer-metrics/micrometer/pull/2977
> Exporting fixed bucket histograms

- custom/build.gradle.kts
- custom/src/main/java/com/splunk/opentelemetry/micrometer/CustomSignalFxConfig.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/CustomSignalFxMeterRegistry.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstaller.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfig.java
https://github.com/signalfx/splunk-otel-java/pull/679 cherry picked to 1.8.x branch
> Exporting fixed bucket histograms (v1.8.x)

- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- custom/build.gradle.kts
- profiler/src/main/java/com/splunk/opentelemetry/profiler/LogDataCreator.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/TLABProcessor.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/LogDataCreatorTest.java
Fixes #695 
Fixes #691 
Fixes #690
> Bump OTel SDK version to 1.12.0

- instrumentation/servlet/src/main/java/com/splunk/opentelemetry/instrumentation/servlet/ServletInstrumentationModule.java
- instrumentation/servlet/src/test/java/com/splunk/opentelemetry/instrumentation/servlet/ServletInstrumentationTest.java
Servlet instrumentation currently overwrites `Server-Timings` header upon entering every filter/servlet invocation. This causes it to be set to an internal span if one of those filters switched span context to an internal span that is a child of the server span. Added a call depth filter to the instrumentation to only do it for the outermost filter/servlet that has a valid span context, and a test to verify it (made sure test fails without the fix).
Had to update OpenTelemetry SDK versions used, since the latest instrumentation version was just switched to use new SDK version as well (exploded when trying to find recently added histogram classes otherwise).
> Fix servlet instrumentation using internal spans for Server-Timings header

- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/ConnectionPoolSemanticConventions.java
- bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/ThreadPoolSemanticConventions.java
- docs/metrics.md
- instrumentation/c3p0/src/main/java/com/splunk/opentelemetry/instrumentation/c3p0/ConnectionPoolMetrics.java
- instrumentation/c3p0/src/test/java/com/splunk/opentelemetry/instrumentation/c3p0/C3p0InstrumentationTest.java
- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/instrumentation/commonsdbcp2/DataSourceMetrics.java
- instrumentation/commons-dbcp2/src/test/java/com/splunk/opentelemetry/instrumentation/commonsdbcp2/CommonsDbcp2InstrumentationTest.java
- instrumentation/hikaricp/src/main/java/com/splunk/opentelemetry/instrumentation/hikaricp/MicrometerMetricsTracker.java
- instrumentation/hikaricp/src/test/java/com/splunk/opentelemetry/instrumentation/hikaricp/HikariInstrumentationTest.java
- instrumentation/oracle-ucp/src/main/java/com/splunk/opentelemetry/instrumentation/oracleucp/ConnectionPoolMetrics.java
- instrumentation/oracle-ucp/src/test/java/com/splunk/opentelemetry/instrumentation/oracleucp/UcpInstrumentationTest.java
- instrumentation/tomcat-jdbc/src/main/java/com/splunk/opentelemetry/instrumentation/tomcatjdbc/ConnectionPoolMetrics.java
- instrumentation/tomcat-jdbc/src/test/java/com/splunk/opentelemetry/instrumentation/tomcatjdbc/TomcatJdbcInstrumentationTest.java
- instrumentation/vibur-dbcp/src/main/java/com/splunk/opentelemetry/instrumentation/viburdbcp/ConnectionPoolMetrics.java
- instrumentation/vibur-dbcp/src/test/java/com/splunk/opentelemetry/instrumentation/viburdbcp/ViburDbcpInstrumentationTest.java
> Document metric types

- smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JaegerAndB3SpringBootSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
> Fix CI build - correctly compute instrumentation version in smoke tests

- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- custom/src/test/java/com/splunk/opentelemetry/ServiceNameCheckerTest.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfigTest.java
> Remove deprecated method calls, upgrade micrometer

- scripts/post-release.sh
- scripts/release.sh
Also see https://github.com/signalfx/splunk-otel-java-overhead-test/pull/43
> Automate overhead tests (and post-release PR)

- scripts/post-release.sh
- scripts/release.sh
https://github.com/signalfx/splunk-otel-java/pull/747 (commit 8d76e5e3755c92e3d51c9fbc451debd73f17d1df) cherry picked to 1.10.x branch
> Automate overhead tests (and post-release PR) (v1.10.x)

- scripts/release.sh
Turns out that key id was wrong -- I added the correct one to GitLab CI/CD variables and verified that it works.
> Fix release automation script

- .github/workflows/nightly-failed.template
- .github/workflows/nightly.yaml
- scripts/release.sh
Replaced the `JasonEtco/create-an-issue` action with `gh issue create`, changed the PRs created after the release a tiny bit (add `automated` label)
> Minor GHA and release scripts refactoring

- docs/metrics.md
- instrumentation/c3p0/src/main/java/com/splunk/opentelemetry/instrumentation/c3p0/C3p0InstrumentationModule.java
- instrumentation/commons-dbcp2/src/main/java/com/splunk/opentelemetry/instrumentation/commonsdbcp2/CommonsDbcp2InstrumentationModule.java
- instrumentation/hikaricp/src/main/java/com/splunk/opentelemetry/instrumentation/hikaricp/HikariInstrumentationModule.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsInstaller.java
- instrumentation/liberty/src/main/java/com/splunk/opentelemetry/instrumentation/liberty/metrics/LibertyMetricsInstrumentationModule.java
- instrumentation/oracle-ucp/src/main/java/com/splunk/opentelemetry/instrumentation/oracleucp/OracleUcpInstrumentationModule.java
- instrumentation/tomcat-jdbc/src/main/java/com/splunk/opentelemetry/instrumentation/tomcatjdbc/TomcatJdbcInstrumentationModule.java
- instrumentation/tomcat/src/main/java/com/splunk/opentelemetry/instrumentation/tomcat/metrics/TomcatMetricsInstrumentationModule.java
- instrumentation/vibur-dbcp/src/main/java/com/splunk/opentelemetry/instrumentation/viburdbcp/ViburDbcpInstrumentationModule.java
- instrumentation/weblogic/src/main/java/com/splunk/opentelemetry/instrumentation/weblogic/metrics/WebLogicMetricsInstrumentationModule.java
Changed some of our metric instrumentations' names, in preparation for the coming metrics work.
> Rename metrics instrumentations

- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
> Bump OTel SDK version

- README.md
> v1.11.0 post release changes

- README.md
> v1.12.0 post release changes

- CHANGELOG.md
- README.md
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
Resolves https://github.com/signalfx/splunk-otel-java/issues/817
> Update otel and micrometer dependencies

- README.md
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
> v1.13.0 post release changes

- custom/src/main/java/com/splunk/opentelemetry/RealmAccessTokenChecker.java
- custom/src/main/java/com/splunk/opentelemetry/ServiceNameChecker.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerInstaller.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfig.java
- custom/src/main/java/com/splunk/opentelemetry/resource/ResourceAttributesToSystemProperties.java
- custom/src/test/java/com/splunk/opentelemetry/RealmAccessTokenCheckerTest.java
- custom/src/test/java/com/splunk/opentelemetry/ServiceNameCheckerTest.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfigTest.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/JvmMetricsInstaller.java
- testing/agent-test-extension/src/main/java/com/splunk/opentelemetry/testing/TestMicrometerInstaller.java
Resolves https://github.com/signalfx/splunk-otel-java/issues/837
> Fix build after upstream changes

- README.md
> v1.14.0 post release changes

- custom/src/main/java/com/splunk/opentelemetry/micrometer/MicrometerBootstrapPackagesProvider.java
- custom/src/main/java/com/splunk/opentelemetry/webengine/WebengineBootstrapPackagesProvider.java
- instrumentation/khttp/src/main/java/com/splunk/opentelemetry/instrumentation/khttp/KHttpSingletons.java
- testing/agent-test-extension/src/main/java/com/splunk/opentelemetry/testing/IgnoredTestTypesConfigurer.java
> Fix CI build; remove some deprecations

- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfig.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkConfigurationTest.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfigTest.java
+ added some more `SplunkConfiguration` unit tests
> [bugfix] Memory profiler should turn on metrics

- CHANGELOG.md
- README.md
- custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java
- custom/src/main/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfig.java
- custom/src/test/java/com/splunk/opentelemetry/SplunkConfigurationTest.java
- custom/src/test/java/com/splunk/opentelemetry/micrometer/SplunkMetricsConfigTest.java
- deployments/cloudfoundry/buildpack/README.md
* Cherry picks ec709753edacd136b9a0c7ff0bfd5e874f9c1d92 
* Updates README and CHANGELOG for patch release v1.14.1
> Prepare v1.14.1

- CHANGELOG.md
- README.md
- deployments/cloudfoundry/buildpack/README.md
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/micrometer/MicrometerAllocatedMemoryMetrics.java
Cherry pick e9aff79245b4e21da118ddb42b6f34fd9bb46366 and update `CHANGELOG.md` and `README.md` for patch release.
> Pre v1.14.2

- README.md
- deployments/cloudfoundry/index.yml
- scripts/publish-docker-image.sh
\+ a fix for the docker image build
> v1.16.0 post release changes

- custom/src/main/java/com/splunk/opentelemetry/jaeger/JaegerThriftSpanExporterFactory.java
Inspired by https://github.com/signalfx/gdi-specification/pull/191 and should probably wait until that one is merged.
> Log deprecation warning for jaeger thrift exporter.

- README.md
- deployments/cloudfoundry/index.yml
> v1.17.0 post release changes

- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
> Update protobuf-bom to latest (mitigate CVE-2022-3171)

- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrActivator.java
And log a specific warning about the failure modes:
* exists and couldn't be created
* exists but is not a directory
* exists but is not writable
> Check for output dir writability before starting profiler

- .github/workflows/ci.yaml
- .github/workflows/nightly.yaml
- .github/workflows/pr.yaml
- scripts/common.sh
- scripts/pre-release-changes.sh
- scripts/propagate-version.sh
- scripts/publish-docker-image.sh
- scripts/release.sh
- scripts/tag-release.sh
- scripts/update-version-after-release.sh
No more stupid shell mistakes 💯
> Add shellcheck for the release scripts

- README.md
- deployments/cloudfoundry/index.yml
> v1.18.0 post release changes

- profiler/README.md
Add clarification about config preference and metrics
> Update profiling README

- CHANGELOG.md
- README.md
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- instrumentation/micrometer-testing/build.gradle.kts
> Upgrade micrometer version

- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- custom/src/main/java/com/splunk/opentelemetry/SplunkDistroVersionResourceProvider.java
- profiler/src/main/java/com/splunk/opentelemetry/profiler/JfrSettingsReader.java
- profiler/src/test/java/com/splunk/opentelemetry/profiler/ThreadDumpRegionTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/windows/WindowsTestContainerManager.java
In preparation of the release...
> Update to instrumentation and core 1.21.0.

- README.md
- deployments/cloudfoundry/index.yml
> v1.19.0 post release changes

- settings.gradle.kts
- smoke-tests/build.gradle.kts
Checking to see if this is like #1053 but without the build fails.
> Update gradle enterprise remove test-retry

- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
> Bump OTel SDK to 1.22.0

- README.md
- buildSrc/src/main/kotlin/splunk.java-conventions.gradle.kts
- instrumentation/micrometer-testing/build.gradle.kts
> Bump micrometer version to 1.10.3

- README.md
- deployments/cloudfoundry/index.yml
> v1.20.0 post release changes

- dependencyManagement/build.gradle.kts
- smoke-tests/src/test/java/com/splunk/opentelemetry/GlassFishSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JBossEapSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JaegerAndB3SpringBootSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/JettySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/LibertySmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/RulesBasedSamplerSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomcatSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/TomeeSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WebLogicSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/WildFlySmokeTest.java
- smoke-tests/src/test/resources/tlab-sanity-test-app/TlabSanityTestApp.java
Fix for #1114
Fixes #1114 
Fixes #1118 
Fixes #1120
> Bunch of build fixes with upstream updates.

- profiler/src/main/java/com/splunk/opentelemetry/profiler/SdkCustomizer.java
Not sure how we feel about using classes in the upstream `internal` packages, but I thought it maybe seemed like a bad idea. I found another way about this here....curious what we think.
There are usages of `EmbeddedInstrumentationProperties` in `ThreadPoolMetrics` but I didn't touch that because I'm not aware of a replacement...
> Remove usage of internal ConfigPropertiesUtil class

- CHANGELOG.md
- README.md
- dependencyManagement/build.gradle.kts
- deployments/cloudfoundry/buildpack/README.md
Waiting for the signalfx-java release before merging this
> Prepare for release 1.21.0

- custom/src/main/java/com/splunk/opentelemetry/RuleBasedSamplerProvider.java
- dependencyManagement/build.gradle.kts
Just like #1136 but with the matching code changes.
> Bump otelContribAlphaVersion from 1.22.0-alpha to 1.23.0-alpha

- README.md
- deployments/cloudfoundry/index.yml
> v1.22.0 post release changes

- CONTRIBUTING.md
Resolves #1189
Again, this is the only change required - we've already done everything else.
> Conform with GDI spec v1.5.0

- buildSrc/src/main/kotlin/splunk.instrumentation-conventions.gradle.kts
Seems like arguments added with `CommandLineArgumentProvider` are added last to the command line. This means that when `-javaagent` is added this way it will appear after debugger arguments added by intellij which allows debugging agent startup logic in instrumentation tests.
> Use CommandLineArgumentProvider to add javaagent

- instrumentation/khttp-0.1/src/main/java/com/splunk/opentelemetry/instrumentation/khttp/KHttpHttpClientHttpAttributesGetter.java
- instrumentation/khttp-0.1/src/test/groovy/com/splunk/opentelemetry/instrumentation/khttp/KHttpClientTest.groovy
Fixes #1199
Fixes #1200
Fixes #1201 
Fixes #1202
> Fix KHttp tests

- CHANGELOG.md
Add a little more detail about the changes included in 1.23.0.
> Update changelog for 1.23.0

- README.md
- deployments/cloudfoundry/index.yml
> v1.23.0 post release changes

- custom/src/main/java/com/splunk/opentelemetry/logging/SplunkSlf4jLoggingCustomizer.java
Resolves https://github.com/signalfx/splunk-otel-java/issues/1252
Resolves https://github.com/signalfx/splunk-otel-java/issues/1254
> Fix build failure

- README.md
- deployments/cloudfoundry/index.yml
> v1.24.0 post release changes

- instrumentation/khttp-0.1/src/main/java/com/splunk/opentelemetry/instrumentation/khttp/KHttpHttpClientHttpAttributesGetter.java
> Switch to new method name

- README.md
- deployments/cloudfoundry/index.yml
> v1.25.0 post release changes

- scripts/install-gh-deps.sh
- scripts/propagate-version.sh
This is handled in the helm repo itself now.
> Remove parts related to helm version PR

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v1.26.0 post release changes

- buildSrc/build.gradle.kts
- dependencyManagement/build.gradle.kts
- licenses/licenses.md
> Bump contrib dep and remove unneeded plugin

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/1394
> Update otel version to 1.29.0

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v1.27.0 post release changes

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v1.28.0 post release changes

- CONTRIBUTING.md
- README.md
- custom/src/main/java/com/splunk/opentelemetry/servicename/ServiceNameChecker.java
> Update gdi spec 1.6.0

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v1.29.0 post release changes

- .github/workflows/publish-docker-image-ghcr.yml
> ppc64 -> ppc64le for docker image distributions

- .github/renovate.json5
- renovate.json
Also add `docker.repo.splunkdev.net/ci-cd/ci-container/maven-3.8-jdk-17` to ignored packages
> Move renovate configuration

- .github/workflows/ci.yaml
- .github/workflows/nightly.yaml
- .github/workflows/pr.yaml
- .github/workflows/publish-profiling-petclinic-base.yml
> Update ubuntu version in workflows

- smoke-tests/src/test/resources/otel.yaml
Resolves https://github.com/signalfx/splunk-otel-java/issues/1502
> Fix smoke test collector conf

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v1.30.0 post release changes

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
- smoke-tests/src/test/java/com/splunk/opentelemetry/OtlpLogsSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/ProfilerAllocationSanityTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/ProfilerSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/RulesBasedSamplerSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/SpringBootSmokeTest.java
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/AbstractTestContainerManager.java
- smoke-tests/src/test/resources/otel.yaml
Resolves https://github.com/signalfx/splunk-otel-java/issues/1570
Resolves https://github.com/signalfx/splunk-otel-java/issues/1571
Resolves https://github.com/signalfx/splunk-otel-java/issues/1572
Resolves https://github.com/signalfx/splunk-otel-java/issues/1574
> Use http/protobuf in smoke tests

- buildSrc/build.gradle.kts
- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/1588
> Update upstream version to 2.0.0

- docs/metrics.md
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelGcMemoryMetrics.java
- metadata-generator/src/main/java/com/splunk/opentelemetry/tools/MetadataGenerator.java
Not needed according to @gsmirnov-splk
> Remove gc live data size metric

- docs/metrics.md
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/GcMemoryMetrics.java
- instrumentation/jvm-metrics/src/main/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/otel/OtelGcMemoryMetrics.java
- instrumentation/jvm-metrics/src/test/java/com/splunk/opentelemetry/instrumentation/jvmmetrics/OtelJvmMetricsTest.java
- metadata-generator/src/main/java/com/splunk/opentelemetry/tools/MetadataGenerator.java
Not needed according to @gsmirnov-splk
> Remove reclaimed metric

- .github/renovate.json5
> Enable renovate on v1.30.x branch

- deployments/cloudfoundry/buildpack/manifest.yml
When we are ready for 2.0.0 CF integration, we can leverage this.
> cflinuxfs3 -> cflinuxfs4

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
v2.0.0-alpha post release changes
> v2.0.0-alpha post release changes

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
v2.1.0-alpha post release changes
> v2.1.0-alpha post release changes

- .github/renovate.json5
Please don't merge any of the renovate updates to `v1.30.x`
> Switch renovate to v1.31.x branch

- CHANGELOG.md
- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v1.31.0 post release changes

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/1715
Resolves https://github.com/signalfx/splunk-otel-java/issues/1716
> Update otel sdk to 1.36.0

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
v2.2.0-alpha post release changes
> v2.2.0-alpha post release changes

- .github/workflows/pr.yaml
- metadata-generator/src/main/java/com/splunk/opentelemetry/tools/MetadataGenerator.java
Also upload metadata yaml as build artifact
> Add system properties to metadata yaml

- README.md
- smoke-tests/src/test/java/com/splunk/opentelemetry/helper/AbstractTestContainerManager.java
A little bit of low-impact cleanup while working on a configuration related discussion.
> Remove legacy 1x remnants

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
v2.4.0-alpha post release changes
> v2.4.0-alpha post release changes

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/1881
Resolves https://github.com/signalfx/splunk-otel-java/issues/1887
> Update otel sdk to 1.39.0

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.5.0 post release changes

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.6.0 post release changes

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/1994 https://github.com/signalfx/splunk-otel-java/issues/2000
> Update otel sdk to 1.41.0

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.7.0 post release changes

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/2037
Resolves https://github.com/signalfx/splunk-otel-java/issues/2040
> Update otel sdk to 1.42.1

- CHANGELOG.md
- deployments/cloudfoundry/index.yml
I forgot to do this for previous patch releases.
> Post release changes

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/2085
Resolves https://github.com/signalfx/splunk-otel-java/issues/2086
> Update otel sdk to 1.43.0

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.9.0 post release changes

- scripts/publish-docker-image.sh
Creating the PR failed during last release as the target repository is archived. Also looking at https://github.com/signalfx/splunk-otel-collector-operator/pulls?q=is%3Apr+is%3Aclosed I'd say these PRs weren't used anyway.
> Don't create PR for splunk-otel-collector-operator during release

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/2105
Resolves https://github.com/signalfx/splunk-otel-java/issues/2107
Resolves https://github.com/signalfx/splunk-otel-java/issues/2109
> Update otel sdk to 1.44.1

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.10.0 post release changes

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/2125
Resolves https://github.com/signalfx/splunk-otel-java/issues/2126
Resolves https://github.com/signalfx/splunk-otel-java/issues/2127
> Update otel sdk to 1.45.0

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.11.0 post release changes

- README.md
- dependencyManagement/build.gradle.kts
- deployments/cloudfoundry/index.yml
- licenses/licenses.md
- version.gradle.kts
> v2.12.0 post release changes

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.13.0 post release changes

- profiler/src/test/java/com/splunk/opentelemetry/profiler/snapshot/SnapshotSpanAttributeTest.java
The interaction of #2195 and #2197 caused test added in #2197 to fail. This PR fixes those failing tests.
> Fix failing tests in SnapshotSpanAttributeTest.

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.14.0 post release changes

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/2259
Resolves https://github.com/signalfx/splunk-otel-java/issues/2261
Resolves https://github.com/signalfx/splunk-otel-java/issues/2264
> Update otel sdk to 1.49.0

- agent-csa-bundle/build.gradle.kts
continuation of https://github.com/signalfx/splunk-otel-java/pull/2292
> Second attempt at fixing gitlab build

- metadata-generator/src/main/java/com/splunk/opentelemetry/tools/MetadataGenerator.java
Classify metrics as either bundled or custom.
> Classify metrics in the metadata

- dependencyManagement/build.gradle.kts
- licenses/licenses.md
Resolves https://github.com/signalfx/splunk-otel-java/issues/2308
Resolves https://github.com/signalfx/splunk-otel-java/issues/2311
Resolves https://github.com/signalfx/splunk-otel-java/issues/2312
Resolves https://github.com/signalfx/splunk-otel-java/issues/2313
> Update upstream version

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.17.0 post release changes

- README.md
- deployments/cloudfoundry/index.yml
- version.gradle.kts
> v2.18.0 post release changes

- .github/workflows/ci.yaml
- .github/workflows/nightly.yaml
- .github/workflows/pr.yaml
Will close #2399 and do this here until https://github.com/lycheeverse/lychee/issues/1729 can be fixed.
> pin lychee version
